#include "K2Node_SetNamedInstanceData.h"

#include "BlueprintActionDatabaseRegistrar.h"
#include "BlueprintNodeSpawner.h"
#include "Components/InstancedStaticMeshComponent.h"
#include "EdGraphSchema_K2.h"
#include "InstanceDataSetLibrary.h"
#include "K2Node_CallFunction.h"
#include "Kismet/KismetMathLibrary.h"
#include "Kismet2/BlueprintEditorUtils.h"
#include "Kismet2/CompilerResultsLog.h"
#include "KismetCompiler.h"
#include "NamedDataNodeExpansion.h"
#include "Styling/AppStyle.h"

#define LOCTEXT_NAMESPACE "K2Node_SetNamedInstanceData"

// A self pin, so several meshes or an array can be wired in - see UK2Node_SetNamedPrimitiveData.
const FName UK2Node_SetNamedInstanceData::TargetPinName(UEdGraphSchema_K2::PN_Self);
const FName UK2Node_SetNamedInstanceData::InstanceIndexPinName(TEXT("InstanceIndex"));
const FName UK2Node_SetNamedInstanceData::LegendPinName(TEXT("Legend"));
const FName UK2Node_SetNamedInstanceData::ParameterPinName(TEXT("Parameter"));
const FName UK2Node_SetNamedInstanceData::ValuePinName(TEXT("Value"));
const FName UK2Node_SetNamedInstanceData::MarkRenderStateDirtyPinName(TEXT("bMarkRenderStateDirty"));

namespace SetNamedInstanceData
{
	const TCHAR* DefaultColor = TEXT("(R=1.000000,G=1.000000,B=1.000000,A=1.000000)");
	const TCHAR* DefaultScalar = TEXT("0.0");
}

// ---------------------------------------------------------------------------
// Pins
// ---------------------------------------------------------------------------

void UK2Node_SetNamedInstanceData::AllocateDefaultPins()
{
	CreatePin(EGPD_Input, UEdGraphSchema_K2::PC_Exec, UEdGraphSchema_K2::PN_Execute);
	CreatePin(EGPD_Output, UEdGraphSchema_K2::PC_Exec, UEdGraphSchema_K2::PN_Then);

	UEdGraphPin* Target = CreatePin(EGPD_Input, UEdGraphSchema_K2::PC_Object, UInstancedStaticMeshComponent::StaticClass(), TargetPinName);
	Target->PinFriendlyName = LOCTEXT("TargetName", "Target");
	Target->PinToolTip = LOCTEXT("TargetTooltip",
		"The instanced static mesh to set the data on. Wire in several, or an array, to set the same instance on each.").ToString();

	UEdGraphPin* Instance = CreatePin(EGPD_Input, UEdGraphSchema_K2::PC_Int, InstanceIndexPinName);
	Instance->PinToolTip = LOCTEXT("InstanceTooltip", "Which instance to set the data on.").ToString();
	GetDefault<UEdGraphSchema_K2>()->SetPinAutogeneratedDefaultValue(Instance, TEXT("0"));

	// Choices made on the node, not data: only the default-value widget is left.
	UEdGraphPin* Legend = CreatePin(EGPD_Input, UEdGraphSchema_K2::PC_Object, UInstanceDataLegend::StaticClass(), LegendPinName);
	Legend->bNotConnectable = true;
	Legend->PinToolTip = LOCTEXT("LegendTooltip", "The Instance Data Legend that names the parameters.").ToString();

	UEdGraphPin* Parameter = CreatePin(EGPD_Input, UEdGraphSchema_K2::PC_Name, ParameterPinName);
	Parameter->bNotConnectable = true;
	Parameter->PinToolTip = LOCTEXT("ParameterTooltip", "Which of the legend's parameters to set.").ToString();

	CreateValuePin();

	// The engine call's own option, tucked away as the engine tucks it.
	UEdGraphPin* Dirty = CreatePin(EGPD_Input, UEdGraphSchema_K2::PC_Boolean, MarkRenderStateDirtyPinName);
	Dirty->PinFriendlyName = LOCTEXT("DirtyName", "Mark Render State Dirty");
	Dirty->PinToolTip = LOCTEXT("DirtyTooltip",
		"Rebuild the mesh's render state now. Not needed for the change to show; expensive, so not every frame.").ToString();
	Dirty->bAdvancedView = true;
	GetDefault<UEdGraphSchema_K2>()->SetPinAutogeneratedDefaultValue(Dirty, TEXT("false"));
	if (AdvancedPinDisplay == ENodeAdvancedPins::NoPins)
	{
		AdvancedPinDisplay = ENodeAdvancedPins::Hidden;
	}

	Super::AllocateDefaultPins();
}

void UK2Node_SetNamedInstanceData::CreateValuePin()
{
	UEdGraphPin* Value = nullptr;
	switch (ValueKind)
	{
	case ENamedPrimitiveDataValueKind::Scalar:
		Value = CreatePin(EGPD_Input, UEdGraphSchema_K2::PC_Real, UEdGraphSchema_K2::PC_Float, ValuePinName);
		GetDefault<UEdGraphSchema_K2>()->SetPinAutogeneratedDefaultValue(Value, SetNamedInstanceData::DefaultScalar);
		break;
	case ENamedPrimitiveDataValueKind::Vector:
		Value = CreatePin(EGPD_Input, UEdGraphSchema_K2::PC_Struct, TBaseStructure<FLinearColor>::Get(), ValuePinName);
		GetDefault<UEdGraphSchema_K2>()->SetPinAutogeneratedDefaultValue(Value, SetNamedInstanceData::DefaultColor);
		Value->PinToolTip = LOCTEXT("VectorTooltip", "Red, green and blue go to the three floats; alpha is not stored.").ToString();
		break;
	default:
		// No parameter chosen: no Value pin, rather than a wildcard that would accept anything and then fail.
		break;
	}
}

UEdGraphPin* UK2Node_SetNamedInstanceData::FindPinIn(FName Name, const TArray<UEdGraphPin*>* InPins) const
{
	const TArray<UEdGraphPin*>& Search = InPins ? *InPins : Pins;
	for (UEdGraphPin* Pin : Search)
	{
		if (Pin && Pin->PinName == Name)
		{
			return Pin;
		}
	}
	return nullptr;
}

UInstanceDataLegend* UK2Node_SetNamedInstanceData::GetLegend(const TArray<UEdGraphPin*>* InPins) const
{
	const UEdGraphPin* Pin = FindPinIn(LegendPinName, InPins);
	return Pin ? Cast<UInstanceDataLegend>(Pin->DefaultObject) : nullptr;
}

const FInstanceDataLegendEntry* UK2Node_SetNamedInstanceData::ResolveParameter(const TArray<UEdGraphPin*>* InPins) const
{
	const UInstanceDataLegend* Legend = GetLegend(InPins);
	if (!Legend)
	{
		return nullptr;
	}
	if (const FInstanceDataLegendEntry* ById = Legend->FindParameter(ParameterId))
	{
		return ById;
	}
	const UEdGraphPin* Pin = FindPinIn(ParameterPinName, InPins);
	return Pin ? Legend->FindParameter(FName(*Pin->DefaultValue)) : nullptr;
}

ENamedPrimitiveDataValueKind UK2Node_SetNamedInstanceData::KindOf(const FInstanceDataLegendEntry* Entry)
{
	if (!Entry)
	{
		return ENamedPrimitiveDataValueKind::None;
	}
	return Entry->Type == EInstanceDataParameterType::Vector
		? ENamedPrimitiveDataValueKind::Vector
		: ENamedPrimitiveDataValueKind::Scalar;
}

void UK2Node_SetNamedInstanceData::RefreshSelection(const TArray<UEdGraphPin*>* InPins)
{
	const FInstanceDataLegendEntry* Entry = ResolveParameter(InPins);
	if (Entry)
	{
		ParameterId = Entry->Id;
		ParameterName = Entry->Name;
	}
	// A selection the legend no longer has keeps its GUID, so an undo in the legend brings it back; the
	// kind still drops, so the node cannot compile against a type that is no longer there.
	ValueKind = KindOf(Entry);
}

void UK2Node_SetNamedInstanceData::SetValueKind(ENamedPrimitiveDataValueKind NewKind)
{
	if (NewKind == ValueKind)
	{
		return;
	}

	Modify();
	if (UEdGraphPin* Old = FindPin(ValuePinName))
	{
		Old->BreakAllPinLinks();
		RemovePin(Old);
	}
	ValueKind = NewKind;
	CreateValuePin();

	// CreatePin appends; put Value back above the advanced pin, where AllocateDefaultPins makes it.
	if (UEdGraphPin* Value = FindPin(ValuePinName))
	{
		const int32 DirtyIndex = Pins.IndexOfByPredicate([](const UEdGraphPin* Pin) { return Pin->PinName == MarkRenderStateDirtyPinName; });
		if (DirtyIndex != INDEX_NONE)
		{
			Pins.Remove(Value);
			Pins.Insert(Value, DirtyIndex);
		}
	}

	if (UEdGraph* Graph = GetGraph())
	{
		Graph->NotifyNodeChanged(this);
	}
	if (UBlueprint* Blueprint = FBlueprintEditorUtils::FindBlueprintForNode(this))
	{
		FBlueprintEditorUtils::MarkBlueprintAsModified(Blueprint);
	}
}

void UK2Node_SetNamedInstanceData::PinDefaultValueChanged(UEdGraphPin* Pin)
{
	Super::PinDefaultValueChanged(Pin);
	if (!Pin)
	{
		return;
	}

	if (Pin->PinName == LegendPinName)
	{
		Modify();

		// Keep the current parameter if the new legend has it too, otherwise take the first one.
		const UInstanceDataLegend* Legend = GetLegend();
		const FInstanceDataLegendEntry* Entry = ResolveParameter();
		if (!Entry && Legend && Legend->Parameters.Num() > 0)
		{
			Entry = &Legend->Parameters[0];
		}

		ParameterId = Entry ? Entry->Id : FGuid();
		ParameterName = Entry ? Entry->Name : NAME_None;
		if (UEdGraphPin* ParameterPin = FindPin(ParameterPinName))
		{
			ParameterPin->DefaultValue = ParameterName.IsNone() ? FString() : ParameterName.ToString();
		}
		SetValueKind(KindOf(Entry));
	}
	else if (Pin->PinName == ParameterPinName)
	{
		Modify();
		const UInstanceDataLegend* Legend = GetLegend();
		const FInstanceDataLegendEntry* Entry = Legend ? Legend->FindParameter(FName(*Pin->DefaultValue)) : nullptr;
		ParameterId = Entry ? Entry->Id : FGuid();
		ParameterName = Entry ? Entry->Name : NAME_None;
		SetValueKind(KindOf(Entry));
	}
}

void UK2Node_SetNamedInstanceData::ReallocatePinsDuringReconstruction(TArray<UEdGraphPin*>& OldPins)
{
	// The new pins get their defaults only after this returns: read the legend off the old ones.
	if (UInstanceDataLegend* Legend = GetLegend(&OldPins))
	{
		PreloadObject(Legend);
	}
	RefreshSelection(&OldPins);

	Super::ReallocatePinsDuringReconstruction(OldPins);
}

void UK2Node_SetNamedInstanceData::PostReconstructNode()
{
	Super::PostReconstructNode();

	// Reconstruction copied the OLD name back onto the pin; show the one the GUID found.
	if (!ParameterName.IsNone())
	{
		if (UEdGraphPin* ParameterPin = FindPin(ParameterPinName))
		{
			ParameterPin->DefaultValue = ParameterName.ToString();
		}
	}
}

void UK2Node_SetNamedInstanceData::PreloadRequiredAssets()
{
	if (UInstanceDataLegend* Legend = GetLegend())
	{
		PreloadObject(Legend);
	}
	Super::PreloadRequiredAssets();
}

// ---------------------------------------------------------------------------
// Presentation
// ---------------------------------------------------------------------------

FText UK2Node_SetNamedInstanceData::GetNodeTitle(ENodeTitleType::Type TitleType) const
{
	if (TitleType == ENodeTitleType::FullTitle && !ParameterName.IsNone())
	{
		if (const UInstanceDataLegend* Legend = GetLegend())
		{
			return FText::Format(LOCTEXT("TitleWithParameter", "Set Instance {0}\n{1}"),
				FText::FromName(ParameterName), FText::FromString(Legend->GetName()));
		}
	}
	return LOCTEXT("Title", "Set Named Instance Data");
}

FText UK2Node_SetNamedInstanceData::GetTooltipText() const
{
	return LOCTEXT("Tooltip",
		"Set one per instance custom data parameter on an instance of an instanced static mesh, chosen by name "
		"from an Instance Data Legend.\n\n"
		"Compiles to SetCustomDataValue with the slot baked in (one per channel for a vector), so it costs the "
		"same as the hand-wired calls. The mesh needs at least the legend's Floats Per Instance in its Num Custom "
		"Data Floats.");
}

FSlateIcon UK2Node_SetNamedInstanceData::GetIconAndTint(FLinearColor& OutColor) const
{
	static const FSlateIcon Icon(FAppStyle::GetAppStyleSetName(), TEXT("Kismet.AllClasses.FunctionIcon"));
	return Icon;
}

void UK2Node_SetNamedInstanceData::GetMenuActions(FBlueprintActionDatabaseRegistrar& ActionRegistrar) const
{
	UClass* ActionKey = GetClass();
	if (ActionRegistrar.IsOpenForRegistration(ActionKey))
	{
		UBlueprintNodeSpawner* Spawner = UBlueprintNodeSpawner::Create(ActionKey);
		check(Spawner);
		ActionRegistrar.AddBlueprintAction(ActionKey, Spawner);
	}
}

FText UK2Node_SetNamedInstanceData::GetMenuCategory() const
{
	// Beside the engine's own SetCustomDataValue.
	return LOCTEXT("Category", "Components|InstancedStaticMesh");
}

FText UK2Node_SetNamedInstanceData::GetKeywords() const
{
	return LOCTEXT("Keywords", "per instance custom data picd ism hism instanced legend named parameter set");
}

// ---------------------------------------------------------------------------
// Compilation
// ---------------------------------------------------------------------------

void UK2Node_SetNamedInstanceData::ValidateNodeDuringCompilation(FCompilerResultsLog& MessageLog) const
{
	Super::ValidateNodeDuringCompilation(MessageLog);

	const UInstanceDataLegend* Legend = GetLegend();
	if (!Legend)
	{
		MessageLog.Error(*LOCTEXT("NoLegend", "@@ has no Instance Data Legend chosen.").ToString(), this);
		return;
	}

	const FInstanceDataLegendEntry* Entry = ResolveParameter();
	if (!Entry)
	{
		MessageLog.Error(*FText::Format(LOCTEXT("NoParameter", "@@: parameter '{0}' is not in {1}."),
			FText::FromName(ParameterName), FText::FromString(Legend->GetName())).ToString(), this);
		return;
	}
	if (!Entry->HasSlot())
	{
		MessageLog.Error(*FText::Format(
			LOCTEXT("NoSlot", "@@: '{0}' has no slot in {1} - the legend is out of room. Open it for details."),
			FText::FromName(Entry->Name), FText::FromString(Legend->GetName())).ToString(), this);
		return;
	}
	if (KindOf(Entry) != ValueKind)
	{
		MessageLog.Error(*FText::Format(
			LOCTEXT("StaleKind", "@@: '{0}' changed type in {1}. Refresh the node (right-click > Refresh Nodes)."),
			FText::FromName(Entry->Name), FText::FromString(Legend->GetName())).ToString(), this);
	}
}

void UK2Node_SetNamedInstanceData::ExpandNode(FKismetCompilerContext& CompilerContext, UEdGraph* SourceGraph)
{
	Super::ExpandNode(CompilerContext, SourceGraph);

	const UEdGraphSchema_K2* Schema = CompilerContext.GetSchema();
	const FInstanceDataLegendEntry* Entry = ResolveParameter();
	UEdGraphPin* Value = FindPin(ValuePinName);

	// ValidateNodeDuringCompilation has already said why.
	if (!Entry || !Entry->HasSlot() || !Value || KindOf(Entry) != ValueKind)
	{
		BreakAllNodeLinks();
		return;
	}

	UEdGraphPin* Target = FindPinChecked(TargetPinName);
	if (!NamedDataNodeExpansion::CheckSelfTarget(CompilerContext, this, Target, UInstancedStaticMeshComponent::StaticClass(),
		LOCTEXT("NoTarget", "@@ needs an instanced static mesh connected to Target.")))
	{
		BreakAllNodeLinks();
		return;
	}

	UEdGraphPin* Instance = FindPinChecked(InstanceIndexPinName);
	UEdGraphPin* Dirty = FindPinChecked(MarkRenderStateDirtyPinName);
	const int32 Width = Entry->GetWidth();
	bool bWired = true;

	// Several meshes, or an array: SetCustomDataValue returns a bool, and the compiler only loops a call
	// over several targets when it has no outputs. So these go through the plugin's own function, which
	// takes the meshes as an array and loops in C++ - the multiple node's, with every float owned.
	const bool bManyTargets = Target->LinkedTo.Num() > 1
		|| (Target->LinkedTo.Num() == 1 && Target->LinkedTo[0]->PinType.IsArray());
	if (bManyTargets)
	{
		UK2Node_CallFunction* Set = CompilerContext.SpawnIntermediateNode<UK2Node_CallFunction>(this, SourceGraph);
		Set->SetFromFunction(UInstanceDataSetLibrary::StaticClass()->FindFunctionByName(
			GET_FUNCTION_NAME_CHECKED(UInstanceDataSetLibrary, SetInstanceCustomDataMasked)));
		Set->AllocateDefaultPins();

		CompilerContext.MovePinLinksToIntermediate(*GetExecPin(), *Set->GetExecPin());
		CompilerContext.MovePinLinksToIntermediate(*FindPinChecked(UEdGraphSchema_K2::PN_Then), *Set->GetThenPin());
		CompilerContext.MovePinLinksToIntermediate(*Instance, *Set->FindPinChecked(TEXT("InstanceIndex")));
		CompilerContext.MovePinLinksToIntermediate(*Dirty, *Set->FindPinChecked(TEXT("bMarkRenderStateDirty")));
		Schema->TrySetDefaultValue(*Set->FindPinChecked(TEXT("DataIndex")), FString::FromInt(Entry->Slot));
		Schema->TrySetDefaultValue(*Set->FindPinChecked(TEXT("Mask")), FString::FromInt((1 << Width) - 1));

		if (!NamedDataNodeExpansion::GatherTargets(CompilerContext, this, SourceGraph, Target, Set->FindPinChecked(TEXT("Targets")), bWired))
		{
			BreakAllNodeLinks();
			return;
		}
		const NamedDataNodeExpansion::FValueWrite Write{ Value, 0, Width };
		bWired &= NamedDataNodeExpansion::WireValues(CompilerContext, this, SourceGraph, Set->FindPinChecked(TEXT("Values")), Width,
			MakeArrayView(&Write, 1));
		if (!bWired)
		{
			CompilerContext.MessageLog.Error(*LOCTEXT("WireFailed", "@@: internal error wiring the instance data write.").ToString(), this);
		}
		BreakAllNodeLinks();
		return;
	}

	// One engine call per float: a scalar is one, a vector's red, green and blue are three in a row. Each
	// gets the node's Target, instance and dirty flag; the first takes them over, the rest copy them.
	TArray<UK2Node_CallFunction*> Sets;
	for (int32 Float = 0; Float < Width; ++Float)
	{
		UK2Node_CallFunction* Set = CompilerContext.SpawnIntermediateNode<UK2Node_CallFunction>(this, SourceGraph);
		Set->FunctionReference.SetExternalMember(
			GET_FUNCTION_NAME_CHECKED(UInstancedStaticMeshComponent, SetCustomDataValue), UInstancedStaticMeshComponent::StaticClass());
		Set->AllocateDefaultPins();
		// THE point of the node: the slot is a literal, decided now.
		Schema->TrySetDefaultValue(*Set->FindPinChecked(TEXT("CustomDataIndex")), FString::FromInt(Entry->Slot + Float));
		Sets.Add(Set);
	}

	for (int32 Float = 0; Float < Sets.Num(); ++Float)
	{
		UK2Node_CallFunction* Set = Sets[Float];
		const bool bLast = Float == Sets.Num() - 1;
		auto Share = [&CompilerContext, bLast](UEdGraphPin* From, UEdGraphPin* To)
		{
			// The last one moves, so the earlier copies still have links to copy from.
			return (bLast ? CompilerContext.MovePinLinksToIntermediate(*From, *To) : CompilerContext.CopyPinLinksToIntermediate(*From, *To))
				.CanSafeConnect();
		};
		bWired &= Share(Target, Set->FindPinChecked(UEdGraphSchema_K2::PN_Self));
		bWired &= Share(Instance, Set->FindPinChecked(TEXT("InstanceIndex")));
		bWired &= Share(Dirty, Set->FindPinChecked(TEXT("bMarkRenderStateDirty")));
		if (Float > 0)
		{
			bWired &= Schema->TryCreateConnection(Sets[Float - 1]->GetThenPin(), Set->GetExecPin());
		}
	}

	CompilerContext.MovePinLinksToIntermediate(*GetExecPin(), *Sets[0]->GetExecPin());
	CompilerContext.MovePinLinksToIntermediate(*FindPinChecked(UEdGraphSchema_K2::PN_Then), *Sets.Last()->GetThenPin());

	if (Width == 1)
	{
		bWired &= CompilerContext.MovePinLinksToIntermediate(*Value, *Sets[0]->FindPinChecked(TEXT("CustomDataValue"))).CanSafeConnect();
	}
	else
	{
		// One BreakColor feeds all three: an engine function, so the cooked graph needs nothing else.
		UK2Node_CallFunction* Break = CompilerContext.SpawnIntermediateNode<UK2Node_CallFunction>(this, SourceGraph);
		Break->FunctionReference.SetExternalMember(GET_FUNCTION_NAME_CHECKED(UKismetMathLibrary, BreakColor), UKismetMathLibrary::StaticClass());
		Break->AllocateDefaultPins();
		bWired &= CompilerContext.MovePinLinksToIntermediate(*Value, *Break->FindPinChecked(TEXT("InColor"))).CanSafeConnect();
		const TCHAR* Channels[] = { TEXT("R"), TEXT("G"), TEXT("B") };
		for (int32 Channel = 0; Channel < Sets.Num(); ++Channel)
		{
			bWired &= Schema->TryCreateConnection(Break->FindPinChecked(Channels[Channel]), Sets[Channel]->FindPinChecked(TEXT("CustomDataValue")));
		}
	}

	if (!bWired)
	{
		CompilerContext.MessageLog.Error(*LOCTEXT("WireFailed", "@@: internal error wiring the instance data write.").ToString(), this);
	}
	BreakAllNodeLinks();
}

#undef LOCTEXT_NAMESPACE
