#include "K2Node_SetNamedInstanceDataBatch.h"

#include "BlueprintActionDatabaseRegistrar.h"
#include "BlueprintNodeSpawner.h"
#include "Components/InstancedStaticMeshComponent.h"
#include "EdGraphSchema_K2.h"
#include "InstanceDataSetLibrary.h"
#include "K2Node_CallFunction.h"
#include "K2Node_MakeArray.h"
#include "K2Node_MakeStruct.h"
#include "Kismet2/BlueprintEditorUtils.h"
#include "Kismet2/CompilerResultsLog.h"
#include "KismetCompiler.h"
#include "NamedDataNodeExpansion.h"
#include "Styling/AppStyle.h"

#define LOCTEXT_NAMESPACE "K2Node_SetNamedInstanceDataBatch"

const FName UK2Node_SetNamedInstanceDataBatch::TargetPinName(UEdGraphSchema_K2::PN_Self);
const FName UK2Node_SetNamedInstanceDataBatch::InstanceIndicesPinName(TEXT("InstanceIndices"));
const FName UK2Node_SetNamedInstanceDataBatch::LegendPinName(TEXT("Legend"));
const FName UK2Node_SetNamedInstanceDataBatch::MarkRenderStateDirtyPinName(TEXT("bMarkRenderStateDirty"));

namespace SetNamedInstanceDataBatch
{
	const TCHAR* DefaultColor = TEXT("(R=1.000000,G=1.000000,B=1.000000,A=1.000000)");
	const TCHAR* DefaultScalar = TEXT("0.0");

	ENamedPrimitiveDataValueKind KindOf(const FInstanceDataLegendEntry* Entry)
	{
		if (!Entry)
		{
			return ENamedPrimitiveDataValueKind::None;
		}
		return Entry->Type == EInstanceDataParameterType::Vector
			? ENamedPrimitiveDataValueKind::Vector
			: ENamedPrimitiveDataValueKind::Scalar;
	}
}

// ---------------------------------------------------------------------------
// Pins
// ---------------------------------------------------------------------------

FName UK2Node_SetNamedInstanceDataBatch::PinNameFor(const FGuid& Id)
{
	return FName(*FString::Printf(TEXT("Param_%s"), *Id.ToString(EGuidFormats::Digits)));
}

void UK2Node_SetNamedInstanceDataBatch::AllocateDefaultPins()
{
	CreatePin(EGPD_Input, UEdGraphSchema_K2::PC_Exec, UEdGraphSchema_K2::PN_Execute);
	CreatePin(EGPD_Output, UEdGraphSchema_K2::PC_Exec, UEdGraphSchema_K2::PN_Then);

	UEdGraphPin* Target = CreatePin(EGPD_Input, UEdGraphSchema_K2::PC_Object, UInstancedStaticMeshComponent::StaticClass(), TargetPinName);
	Target->PinFriendlyName = LOCTEXT("TargetName", "Target");
	Target->PinToolTip = LOCTEXT("TargetTooltip",
		"The instanced static mesh to set the data on. Wire in several, or an array, to set the same instances on each.").ToString();

	FCreatePinParams ArrayParams;
	ArrayParams.ContainerType = EPinContainerType::Array;
	UEdGraphPin* Instances = CreatePin(EGPD_Input, UEdGraphSchema_K2::PC_Int, InstanceIndicesPinName, ArrayParams);
	Instances->PinToolTip = LOCTEXT("InstancesTooltip",
		"The instances to set. Per instance parameters take their k-th value for the k-th index here. Consecutive "
		"ascending indices are written as one block, the fastest case.").ToString();

	UEdGraphPin* Legend = CreatePin(EGPD_Input, UEdGraphSchema_K2::PC_Object, UInstanceDataLegend::StaticClass(), LegendPinName);
	Legend->bNotConnectable = true;
	Legend->PinToolTip = LOCTEXT("LegendTooltip",
		"The Instance Data Legend that names the parameters. Tick the ones to set, and which take a value per instance, in the Details panel.").ToString();

	for (const FNamedInstanceDataBatchSelection& Selected : Selection)
	{
		CreateValuePin(Selected);
	}

	UEdGraphPin* Dirty = CreatePin(EGPD_Input, UEdGraphSchema_K2::PC_Boolean, MarkRenderStateDirtyPinName);
	Dirty->PinFriendlyName = LOCTEXT("DirtyName", "Mark Render State Dirty");
	Dirty->PinToolTip = LOCTEXT("DirtyTooltip",
		"Rebuild the mesh's render state now. Not needed for the change to show; expensive, so not every frame.").ToString();
	Dirty->bAdvancedView = true;
	GetDefault<UEdGraphSchema_K2>()->SetPinAutogeneratedDefaultValue(Dirty, TEXT("false"));
	if (AdvancedPinDisplay == ENodeAdvancedPins::NoPins)
	{
		AdvancedPinDisplay = ENodeAdvancedPins::Hidden;
	}

	Super::AllocateDefaultPins();
}

void UK2Node_SetNamedInstanceDataBatch::CreateValuePin(const FNamedInstanceDataBatchSelection& Selected)
{
	FCreatePinParams Params;
	Params.ContainerType = Selected.bPerInstance ? EPinContainerType::Array : EPinContainerType::None;

	UEdGraphPin* Value = nullptr;
	switch (Selected.Kind)
	{
	case ENamedPrimitiveDataValueKind::Scalar:
		Value = CreatePin(EGPD_Input, UEdGraphSchema_K2::PC_Real, UEdGraphSchema_K2::PC_Float, PinNameFor(Selected.Id), Params);
		break;
	case ENamedPrimitiveDataValueKind::Vector:
		Value = CreatePin(EGPD_Input, UEdGraphSchema_K2::PC_Struct, TBaseStructure<FLinearColor>::Get(), PinNameFor(Selected.Id), Params);
		break;
	default:
		// No longer in the legend: no pin, and validation says why.
		return;
	}
	if (!Selected.bPerInstance)
	{
		GetDefault<UEdGraphSchema_K2>()->SetPinAutogeneratedDefaultValue(Value, Selected.Kind == ENamedPrimitiveDataValueKind::Vector
			? SetNamedInstanceDataBatch::DefaultColor : SetNamedInstanceDataBatch::DefaultScalar);
	}
	Value->PinFriendlyName = Selected.bPerInstance
		? FText::Format(LOCTEXT("PerInstanceName", "{0} (per instance)"), FText::FromName(Selected.Name))
		: FText::FromName(Selected.Name);
}

void UK2Node_SetNamedInstanceDataBatch::PostReconstructNode()
{
	Super::PostReconstructNode();

	const UInstanceDataLegend* Legend = GetLegend();
	for (const FNamedInstanceDataBatchSelection& Selected : Selection)
	{
		UEdGraphPin* Value = FindValuePin(Selected.Id);
		const FInstanceDataLegendEntry* Entry = Resolve(Legend, Selected);
		if (Value && Entry && Entry->HasSlot())
		{
			const FString Slots = Entry->GetWidth() > 1
				? FString::Printf(TEXT("slots %d-%d; alpha is not stored"), Entry->Slot, Entry->Slot + Entry->GetWidth() - 1)
				: FString::Printf(TEXT("slot %d"), Entry->Slot);
			Value->PinToolTip = Selected.bPerInstance
				? FString::Printf(TEXT("%s (%s). One value per entry of Instance Indices; instances past the end of this array keep theirs."),
					*Selected.Name.ToString(), *Slots)
				: FString::Printf(TEXT("%s (%s). The same value for every instance."), *Selected.Name.ToString(), *Slots);
		}
	}
}

UEdGraphPin* UK2Node_SetNamedInstanceDataBatch::FindPinIn(FName Name, const TArray<UEdGraphPin*>* InPins) const
{
	const TArray<UEdGraphPin*>& Search = InPins ? *InPins : Pins;
	for (UEdGraphPin* Pin : Search)
	{
		if (Pin && Pin->PinName == Name)
		{
			return Pin;
		}
	}
	return nullptr;
}

UEdGraphPin* UK2Node_SetNamedInstanceDataBatch::FindValuePin(const FGuid& Id) const
{
	return FindPinIn(PinNameFor(Id), nullptr);
}

UInstanceDataLegend* UK2Node_SetNamedInstanceDataBatch::GetLegend(const TArray<UEdGraphPin*>* InPins) const
{
	const UEdGraphPin* Pin = FindPinIn(LegendPinName, InPins);
	return Pin ? Cast<UInstanceDataLegend>(Pin->DefaultObject) : nullptr;
}

const FInstanceDataLegendEntry* UK2Node_SetNamedInstanceDataBatch::Resolve(const UInstanceDataLegend* Legend,
	const FNamedInstanceDataBatchSelection& Selected) const
{
	if (!Legend)
	{
		return nullptr;
	}
	if (const FInstanceDataLegendEntry* ById = Legend->FindParameter(Selected.Id))
	{
		return ById;
	}
	return Selected.Name.IsNone() ? nullptr : Legend->FindParameter(Selected.Name);
}

// ---------------------------------------------------------------------------
// Selection
// ---------------------------------------------------------------------------

bool UK2Node_SetNamedInstanceDataBatch::IsParameterSelected(const FGuid& Id) const
{
	return Selection.ContainsByPredicate([&Id](const FNamedInstanceDataBatchSelection& Selected) { return Selected.Id == Id; });
}

void UK2Node_SetNamedInstanceDataBatch::SetParameterSelected(const FGuid& Id, bool bSelected)
{
	if (IsParameterSelected(Id) == bSelected)
	{
		return;
	}

	Modify();
	if (bSelected)
	{
		Selection.AddDefaulted_GetRef().Id = Id;
	}
	else
	{
		Selection.RemoveAll([&Id](const FNamedInstanceDataBatchSelection& Selected) { return Selected.Id == Id; });
		DropValuePin(Id);
	}
	RefreshSelection(nullptr);
	Rebuild();
}

bool UK2Node_SetNamedInstanceDataBatch::IsParameterPerInstance(const FGuid& Id) const
{
	const FNamedInstanceDataBatchSelection* Found =
		Selection.FindByPredicate([&Id](const FNamedInstanceDataBatchSelection& Selected) { return Selected.Id == Id; });
	return Found && Found->bPerInstance;
}

void UK2Node_SetNamedInstanceDataBatch::SetParameterPerInstance(const FGuid& Id, bool bPerInstance)
{
	FNamedInstanceDataBatchSelection* Found =
		Selection.FindByPredicate([&Id](const FNamedInstanceDataBatchSelection& Selected) { return Selected.Id == Id; });
	if (!Found || Found->bPerInstance == bPerInstance)
	{
		return;
	}

	Modify();
	Found->bPerInstance = bPerInstance;
	// The pin changes type: a single value's wire cannot carry over to an array, or back.
	DropValuePin(Id);
	Rebuild();
}

void UK2Node_SetNamedInstanceDataBatch::DropValuePin(const FGuid& Id)
{
	if (UEdGraphPin* Pin = FindValuePin(Id))
	{
		Pin->BreakAllPinLinks();
		RemovePin(Pin);
	}
}

void UK2Node_SetNamedInstanceDataBatch::RefreshSelection(const TArray<UEdGraphPin*>* InPins)
{
	const UInstanceDataLegend* Legend = GetLegend(InPins);
	if (!Legend)
	{
		return;
	}

	for (FNamedInstanceDataBatchSelection& Selected : Selection)
	{
		const FInstanceDataLegendEntry* Entry = Resolve(Legend, Selected);
		if (Entry)
		{
			Selected.Id = Entry->Id;
			Selected.Name = Entry->Name;
		}
		Selected.Kind = SetNamedInstanceDataBatch::KindOf(Entry);
	}

	auto IndexOf = [Legend](const FNamedInstanceDataBatchSelection& Selected)
	{
		const int32 Index = Legend->Parameters.IndexOfByPredicate(
			[&Selected](const FInstanceDataLegendEntry& Entry) { return Entry.Id == Selected.Id; });
		return Index == INDEX_NONE ? MAX_int32 : Index;
	};
	Selection.StableSort([&IndexOf](const FNamedInstanceDataBatchSelection& A, const FNamedInstanceDataBatchSelection& B)
	{
		return IndexOf(A) < IndexOf(B);
	});
}

void UK2Node_SetNamedInstanceDataBatch::Rebuild()
{
	ReconstructNode();
	if (UEdGraph* Graph = GetGraph())
	{
		Graph->NotifyNodeChanged(this);
	}
	if (UBlueprint* Blueprint = FBlueprintEditorUtils::FindBlueprintForNode(this))
	{
		FBlueprintEditorUtils::MarkBlueprintAsModified(Blueprint);
	}
}

void UK2Node_SetNamedInstanceDataBatch::PinDefaultValueChanged(UEdGraphPin* Pin)
{
	Super::PinDefaultValueChanged(Pin);
	if (!Pin || Pin->PinName != LegendPinName)
	{
		return;
	}

	Modify();
	const UInstanceDataLegend* Legend = GetLegend();
	Selection.RemoveAll([this, Legend](const FNamedInstanceDataBatchSelection& Selected)
	{
		if (Resolve(Legend, Selected))
		{
			return false;
		}
		DropValuePin(Selected.Id);
		return true;
	});
	RefreshSelection(nullptr);
	Rebuild();
	OnParametersOffered.Broadcast();
}

void UK2Node_SetNamedInstanceDataBatch::ReallocatePinsDuringReconstruction(TArray<UEdGraphPin*>& OldPins)
{
	if (UInstanceDataLegend* Legend = GetLegend(&OldPins))
	{
		PreloadObject(Legend);
	}
	RefreshSelection(&OldPins);

	Super::ReallocatePinsDuringReconstruction(OldPins);
}

UK2Node::ERedirectType UK2Node_SetNamedInstanceDataBatch::DoPinsMatchForReconstruction(const UEdGraphPin* NewPin,
	int32 NewPinIndex, const UEdGraphPin* OldPin, int32 OldPinIndex) const
{
	if (NewPin && OldPin && NewPin->Direction == OldPin->Direction && NewPin->PinName == OldPin->PinName)
	{
		// A parameter whose type changed in the legend, or that switched between one value and an array.
		const bool bSameType = NewPin->PinType.PinCategory == OldPin->PinType.PinCategory
			&& NewPin->PinType.PinSubCategoryObject == OldPin->PinType.PinSubCategoryObject
			&& NewPin->PinType.ContainerType == OldPin->PinType.ContainerType;
		if (!bSameType)
		{
			return ERedirectType_None;
		}
	}
	return Super::DoPinsMatchForReconstruction(NewPin, NewPinIndex, OldPin, OldPinIndex);
}

void UK2Node_SetNamedInstanceDataBatch::PreloadRequiredAssets()
{
	if (UInstanceDataLegend* Legend = GetLegend())
	{
		PreloadObject(Legend);
	}
	Super::PreloadRequiredAssets();
}

bool UK2Node_SetNamedInstanceDataBatch::GetWriteRange(int32& OutFirst, int32& OutCount, uint64& OutMask) const
{
	OutFirst = 0;
	OutCount = 0;
	OutMask = 0;

	const UInstanceDataLegend* Legend = GetLegend();
	int32 First = MAX_int32;
	int32 End = 0;
	for (const FNamedInstanceDataBatchSelection& Selected : Selection)
	{
		const FInstanceDataLegendEntry* Entry = Resolve(Legend, Selected);
		if (Entry && Entry->HasSlot())
		{
			First = FMath::Min(First, Entry->Slot);
			End = FMath::Max(End, Entry->Slot + Entry->GetWidth());
		}
	}
	if (First == MAX_int32)
	{
		return false;
	}

	for (const FNamedInstanceDataBatchSelection& Selected : Selection)
	{
		const FInstanceDataLegendEntry* Entry = Resolve(Legend, Selected);
		if (Entry && Entry->HasSlot())
		{
			for (int32 Float = 0; Float < Entry->GetWidth(); ++Float)
			{
				OutMask |= uint64(1) << (Entry->Slot - First + Float);
			}
		}
	}
	OutFirst = First;
	OutCount = End - First;
	return true;
}

// ---------------------------------------------------------------------------
// Presentation
// ---------------------------------------------------------------------------

FText UK2Node_SetNamedInstanceDataBatch::GetNodeTitle(ENodeTitleType::Type TitleType) const
{
	if (TitleType == ENodeTitleType::FullTitle)
	{
		if (const UInstanceDataLegend* Legend = GetLegend())
		{
			return FText::Format(LOCTEXT("TitleWithLegend", "Set Named Instance Data (Batch)\n{0}"), FText::FromString(Legend->GetName()));
		}
	}
	return LOCTEXT("Title", "Set Named Instance Data (Batch)");
}

FText UK2Node_SetNamedInstanceDataBatch::GetTooltipText() const
{
	return LOCTEXT("Tooltip",
		"Set per instance custom data parameters on many instances of an instanced static mesh in one call, chosen by "
		"name from an Instance Data Legend. Tick the parameters in the Details panel, and Per Instance for those that "
		"take an array with a value per instance rather than one value for all.\n\n"
		"Loops in C++, not Blueprint: consecutive ascending indices are written as one block, any other order row by "
		"row. Floats the node does not set keep their values.");
}

FSlateIcon UK2Node_SetNamedInstanceDataBatch::GetIconAndTint(FLinearColor& OutColor) const
{
	static const FSlateIcon Icon(FAppStyle::GetAppStyleSetName(), TEXT("Kismet.AllClasses.FunctionIcon"));
	return Icon;
}

void UK2Node_SetNamedInstanceDataBatch::GetMenuActions(FBlueprintActionDatabaseRegistrar& ActionRegistrar) const
{
	UClass* ActionKey = GetClass();
	if (ActionRegistrar.IsOpenForRegistration(ActionKey))
	{
		UBlueprintNodeSpawner* Spawner = UBlueprintNodeSpawner::Create(ActionKey);
		check(Spawner);
		ActionRegistrar.AddBlueprintAction(ActionKey, Spawner);
	}
}

FText UK2Node_SetNamedInstanceDataBatch::GetMenuCategory() const
{
	return LOCTEXT("Category", "Components|InstancedStaticMesh");
}

FText UK2Node_SetNamedInstanceDataBatch::GetKeywords() const
{
	return LOCTEXT("Keywords", "per instance custom data picd ism hism instanced legend named parameter set batch many all instances array bulk");
}

// ---------------------------------------------------------------------------
// Compilation
// ---------------------------------------------------------------------------

void UK2Node_SetNamedInstanceDataBatch::ValidateNodeDuringCompilation(FCompilerResultsLog& MessageLog) const
{
	Super::ValidateNodeDuringCompilation(MessageLog);

	const UInstanceDataLegend* Legend = GetLegend();
	if (!Legend)
	{
		MessageLog.Error(*LOCTEXT("NoLegend", "@@ has no Instance Data Legend chosen.").ToString(), this);
		return;
	}
	if (Selection.Num() == 0)
	{
		MessageLog.Error(*LOCTEXT("NothingTicked", "@@ sets nothing - tick its parameters in the Details panel.").ToString(), this);
		return;
	}
	for (const FNamedInstanceDataBatchSelection& Selected : Selection)
	{
		const FInstanceDataLegendEntry* Entry = Resolve(Legend, Selected);
		if (!Entry)
		{
			MessageLog.Error(*FText::Format(LOCTEXT("NoParameter", "@@: parameter '{0}' is not in {1}."),
				FText::FromName(Selected.Name), FText::FromString(Legend->GetName())).ToString(), this);
		}
		else if (!Entry->HasSlot())
		{
			MessageLog.Error(*FText::Format(
				LOCTEXT("NoSlot", "@@: '{0}' has no slot in {1} - the legend is out of room. Open it for details."),
				FText::FromName(Entry->Name), FText::FromString(Legend->GetName())).ToString(), this);
		}
		else if (SetNamedInstanceDataBatch::KindOf(Entry) != Selected.Kind)
		{
			MessageLog.Error(*FText::Format(
				LOCTEXT("StaleKind", "@@: '{0}' changed type in {1}. Refresh the node (right-click > Refresh Nodes)."),
				FText::FromName(Entry->Name), FText::FromString(Legend->GetName())).ToString(), this);
		}
		else if (Selected.bPerInstance)
		{
			const UEdGraphPin* Pin = FindValuePin(Selected.Id);
			if (Pin && Pin->LinkedTo.Num() == 0)
			{
				MessageLog.Warning(*FText::Format(
					LOCTEXT("EmptyColumn", "@@: '{0}' is per instance but has no array connected, so it sets nothing."),
					FText::FromName(Selected.Name)).ToString(), this);
			}
		}
	}
}

void UK2Node_SetNamedInstanceDataBatch::ExpandNode(FKismetCompilerContext& CompilerContext, UEdGraph* SourceGraph)
{
	Super::ExpandNode(CompilerContext, SourceGraph);

	const UEdGraphSchema_K2* Schema = CompilerContext.GetSchema();
	const UInstanceDataLegend* Legend = GetLegend();

	struct FWrite
	{
		const FInstanceDataLegendEntry* Entry;
		UEdGraphPin* Pin;
		bool bPerInstance;
	};
	TArray<FWrite> Writes;
	bool bValid = Legend != nullptr && Selection.Num() > 0;
	for (const FNamedInstanceDataBatchSelection& Selected : Selection)
	{
		const FInstanceDataLegendEntry* Entry = Resolve(Legend, Selected);
		UEdGraphPin* Pin = FindValuePin(Selected.Id);
		if (!Entry || !Entry->HasSlot() || !Pin || SetNamedInstanceDataBatch::KindOf(Entry) != Selected.Kind)
		{
			bValid = false;
			break;
		}
		Writes.Add({ Entry, Pin, Selected.bPerInstance });
	}
	int32 First = 0;
	int32 Count = 0;
	uint64 AllMask = 0;
	if (!bValid || !GetWriteRange(First, Count, AllMask))
	{
		BreakAllNodeLinks();
		return;
	}

	UEdGraphPin* Target = FindPinChecked(TargetPinName);
	if (!NamedDataNodeExpansion::CheckSelfTarget(CompilerContext, this, Target, UInstancedStaticMeshComponent::StaticClass(),
		LOCTEXT("NoTarget", "@@ needs an instanced static mesh connected to Target.")))
	{
		BreakAllNodeLinks();
		return;
	}

	UK2Node_CallFunction* Set = CompilerContext.SpawnIntermediateNode<UK2Node_CallFunction>(this, SourceGraph);
	Set->SetFromFunction(UInstanceDataSetLibrary::StaticClass()->FindFunctionByName(
		GET_FUNCTION_NAME_CHECKED(UInstanceDataSetLibrary, SetInstanceCustomDataBatch)));
	Set->AllocateDefaultPins();
	if (!Set->GetTargetFunction())
	{
		CompilerContext.MessageLog.Error(*LOCTEXT("MissingFunction",
			"@@: internal error - the instance data function to call was not found.").ToString(), this);
		BreakAllNodeLinks();
		return;
	}

	CompilerContext.MovePinLinksToIntermediate(*GetExecPin(), *Set->GetExecPin());
	CompilerContext.MovePinLinksToIntermediate(*FindPinChecked(UEdGraphSchema_K2::PN_Then), *Set->GetThenPin());
	CompilerContext.MovePinLinksToIntermediate(*FindPinChecked(InstanceIndicesPinName), *Set->FindPinChecked(TEXT("InstanceIndices")));
	CompilerContext.MovePinLinksToIntermediate(*FindPinChecked(MarkRenderStateDirtyPinName), *Set->FindPinChecked(TEXT("bMarkRenderStateDirty")));
	Schema->TrySetDefaultValue(*Set->FindPinChecked(TEXT("DataIndex")), FString::FromInt(First));

	bool bWired = true;
	if (!NamedDataNodeExpansion::GatherTargets(CompilerContext, this, SourceGraph, Target, Set->FindPinChecked(TEXT("Targets")), bWired))
	{
		BreakAllNodeLinks();
		return;
	}

	// One value for every instance: into the Uniform floats, owned by the mask, as on the multiple node.
	uint64 UniformMask = 0;
	TArray<NamedDataNodeExpansion::FValueWrite> Uniform;
	for (const FWrite& Write : Writes)
	{
		if (!Write.bPerInstance)
		{
			const int32 Offset = Write.Entry->Slot - First;
			Uniform.Add({ Write.Pin, Offset, Write.Entry->GetWidth() });
			for (int32 Float = 0; Float < Write.Entry->GetWidth(); ++Float)
			{
				UniformMask |= uint64(1) << (Offset + Float);
			}
		}
	}
	Schema->TrySetDefaultValue(*Set->FindPinChecked(TEXT("Mask")), FString::Printf(TEXT("%lld"), static_cast<int64>(UniformMask)));
	if (Uniform.Num() > 0)
	{
		bWired &= NamedDataNodeExpansion::WireValues(CompilerContext, this, SourceGraph, Set->FindPinChecked(TEXT("Uniform")), Count, Uniform);
	}

	// A value per instance: one column each, made as a struct, gathered into the Columns array.
	UK2Node_MakeArray* Columns = nullptr;
	int32 ColumnCount = 0;
	for (const FWrite& Write : Writes)
	{
		if (!Write.bPerInstance)
		{
			continue;
		}
		if (!Columns)
		{
			Columns = CompilerContext.SpawnIntermediateNode<UK2Node_MakeArray>(this, SourceGraph);
			Columns->AllocateDefaultPins();
			bWired &= Schema->TryCreateConnection(Columns->GetOutputPin(), Set->FindPinChecked(TEXT("Columns")));
			Columns->PinConnectionListChanged(Columns->GetOutputPin());
		}
		else
		{
			Columns->AddInputPin();
		}

		UK2Node_MakeStruct* Column = CompilerContext.SpawnIntermediateNode<UK2Node_MakeStruct>(this, SourceGraph);
		Column->StructType = FInstanceDataColumn::StaticStruct();
		Column->bMadeAfterOverridePinRemoval = true;
		Column->AllocateDefaultPins();
		Schema->TrySetDefaultValue(*Column->FindPinChecked(GET_MEMBER_NAME_CHECKED(FInstanceDataColumn, Offset)),
			FString::FromInt(Write.Entry->Slot - First));
		Schema->TrySetDefaultValue(*Column->FindPinChecked(GET_MEMBER_NAME_CHECKED(FInstanceDataColumn, Width)),
			FString::FromInt(Write.Entry->GetWidth()));
		const FName ValuesMember = Write.Entry->GetWidth() == 1
			? GET_MEMBER_NAME_CHECKED(FInstanceDataColumn, Scalars)
			: GET_MEMBER_NAME_CHECKED(FInstanceDataColumn, Colors);
		bWired &= CompilerContext.MovePinLinksToIntermediate(*Write.Pin, *Column->FindPinChecked(ValuesMember)).CanSafeConnect();

		UEdGraphPin* ColumnOut = nullptr;
		for (UEdGraphPin* Pin : Column->Pins)
		{
			if (Pin->Direction == EGPD_Output)
			{
				ColumnOut = Pin;
				break;
			}
		}
		bWired &= ColumnOut && Schema->TryCreateConnection(ColumnOut, Columns->FindPinChecked(Columns->GetPinName(ColumnCount)));
		++ColumnCount;
	}

	if (!bWired)
	{
		CompilerContext.MessageLog.Error(*LOCTEXT("WireFailed", "@@: internal error wiring the instance data write.").ToString(), this);
	}
	BreakAllNodeLinks();
}

#undef LOCTEXT_NAMESPACE
