#include "K2Node_SetNamedPrimitiveDataMulti.h"

#include "BlueprintActionDatabaseRegistrar.h"
#include "BlueprintNodeSpawner.h"
#include "Components/PrimitiveComponent.h"
#include "EdGraphSchema_K2.h"
#include "K2Node_CallFunction.h"
#include "K2Node_MakeArray.h"
#include "K2Node_Self.h"
#include "Kismet/KismetMathLibrary.h"
#include "Kismet2/BlueprintEditorUtils.h"
#include "Kismet2/CompilerResultsLog.h"
#include "KismetCompiler.h"
#include "PrimitiveDataSetLibrary.h"
#include "Styling/AppStyle.h"

#define LOCTEXT_NAMESPACE "K2Node_SetNamedPrimitiveDataMulti"

// A self pin for the same reason as on the single node: only a self pin takes several wires or an array.
const FName UK2Node_SetNamedPrimitiveDataMulti::TargetPinName(UEdGraphSchema_K2::PN_Self);
const FName UK2Node_SetNamedPrimitiveDataMulti::LegendPinName(TEXT("Legend"));

namespace SetNamedPrimitiveDataMulti
{
	const TCHAR* DefaultColor = TEXT("(R=1.000000,G=1.000000,B=1.000000,A=1.000000)");
	const TCHAR* DefaultScalar = TEXT("0.0");

	/**
	 * Not GET_FUNCTION_NAME_CHECKED: the engine overloads these names (TArray and TConstArrayView), so
	 * taking their address does not compile. ExpandNode checks the function is really there instead.
	 */
	const FName FloatArrayFunction(TEXT("SetCustomPrimitiveDataFloatArray"));
	const FName DefaultFloatArrayFunction(TEXT("SetDefaultCustomPrimitiveDataFloatArray"));

	int32 WidthOf(ENamedPrimitiveDataValueKind Kind)
	{
		return Kind == ENamedPrimitiveDataValueKind::Vector ? 4 : 1;
	}

	ENamedPrimitiveDataValueKind KindOf(const FPrimitiveDataLegendEntry* Entry)
	{
		if (!Entry)
		{
			return ENamedPrimitiveDataValueKind::None;
		}
		return Entry->Type == EPrimitiveDataParameterType::Vector
			? ENamedPrimitiveDataValueKind::Vector
			: ENamedPrimitiveDataValueKind::Scalar;
	}
}

// ---------------------------------------------------------------------------
// Pins
// ---------------------------------------------------------------------------

FName UK2Node_SetNamedPrimitiveDataMulti::PinNameFor(const FGuid& Id)
{
	return FName(*FString::Printf(TEXT("Param_%s"), *Id.ToString(EGuidFormats::Digits)));
}

void UK2Node_SetNamedPrimitiveDataMulti::AllocateDefaultPins()
{
	CreatePin(EGPD_Input, UEdGraphSchema_K2::PC_Exec, UEdGraphSchema_K2::PN_Execute);
	CreatePin(EGPD_Output, UEdGraphSchema_K2::PC_Exec, UEdGraphSchema_K2::PN_Then);

	UEdGraphPin* Target = CreatePin(EGPD_Input, UEdGraphSchema_K2::PC_Object, UPrimitiveComponent::StaticClass(), TargetPinName);
	Target->PinFriendlyName = LOCTEXT("TargetName", "Target");
	Target->PinToolTip = LOCTEXT("TargetTooltip",
		"The mesh (any primitive component) to set the data on. Wire in several, or an array, to set it on each.").ToString();

	UEdGraphPin* Legend = CreatePin(EGPD_Input, UEdGraphSchema_K2::PC_Object, UPrimitiveDataLegend::StaticClass(), LegendPinName);
	Legend->bNotConnectable = true;
	Legend->PinToolTip = LOCTEXT("LegendTooltip",
		"The Primitive Data Legend that names the parameters. Tick the ones to set in the Details panel.").ToString();

	for (const FNamedPrimitiveDataSelection& Selected : Selection)
	{
		CreateValuePin(Selected);
	}

	Super::AllocateDefaultPins();
}

void UK2Node_SetNamedPrimitiveDataMulti::CreateValuePin(const FNamedPrimitiveDataSelection& Selected)
{
	UEdGraphPin* Value = nullptr;
	switch (Selected.Kind)
	{
	case ENamedPrimitiveDataValueKind::Scalar:
		Value = CreatePin(EGPD_Input, UEdGraphSchema_K2::PC_Real, UEdGraphSchema_K2::PC_Float, PinNameFor(Selected.Id));
		GetDefault<UEdGraphSchema_K2>()->SetPinAutogeneratedDefaultValue(Value, SetNamedPrimitiveDataMulti::DefaultScalar);
		break;
	case ENamedPrimitiveDataValueKind::Vector:
		Value = CreatePin(EGPD_Input, UEdGraphSchema_K2::PC_Struct, TBaseStructure<FLinearColor>::Get(), PinNameFor(Selected.Id));
		GetDefault<UEdGraphSchema_K2>()->SetPinAutogeneratedDefaultValue(Value, SetNamedPrimitiveDataMulti::DefaultColor);
		break;
	default:
		// No longer in the legend: no pin, and validation says why.
		return;
	}
	Value->PinFriendlyName = FText::FromName(Selected.Name);
}

void UK2Node_SetNamedPrimitiveDataMulti::PostReconstructNode()
{
	Super::PostReconstructNode();

	// Here rather than as the pins are made: during reconstruction the Legend pin has no value yet.
	const UPrimitiveDataLegend* Legend = GetLegend();
	for (const FNamedPrimitiveDataSelection& Selected : Selection)
	{
		UEdGraphPin* Value = FindValuePin(Selected.Id);
		const FPrimitiveDataLegendEntry* Entry = Resolve(Legend, Selected);
		if (Value && Entry && Entry->HasSlot())
		{
			Value->PinToolTip = Entry->GetWidth() > 1
				? FString::Printf(TEXT("%s (slots %d-%d)"), *Selected.Name.ToString(), Entry->Slot, Entry->Slot + Entry->GetWidth() - 1)
				: FString::Printf(TEXT("%s (slot %d)"), *Selected.Name.ToString(), Entry->Slot);
		}
	}
}

UEdGraphPin* UK2Node_SetNamedPrimitiveDataMulti::FindPinIn(FName Name, const TArray<UEdGraphPin*>* InPins) const
{
	const TArray<UEdGraphPin*>& Search = InPins ? *InPins : Pins;
	for (UEdGraphPin* Pin : Search)
	{
		if (Pin && Pin->PinName == Name)
		{
			return Pin;
		}
	}
	return nullptr;
}

UEdGraphPin* UK2Node_SetNamedPrimitiveDataMulti::FindValuePin(const FGuid& Id) const
{
	return FindPinIn(PinNameFor(Id), nullptr);
}

UPrimitiveDataLegend* UK2Node_SetNamedPrimitiveDataMulti::GetLegend(const TArray<UEdGraphPin*>* InPins) const
{
	const UEdGraphPin* Pin = FindPinIn(LegendPinName, InPins);
	return Pin ? Cast<UPrimitiveDataLegend>(Pin->DefaultObject) : nullptr;
}

const FPrimitiveDataLegendEntry* UK2Node_SetNamedPrimitiveDataMulti::Resolve(const UPrimitiveDataLegend* Legend,
	const FNamedPrimitiveDataSelection& Selected) const
{
	if (!Legend)
	{
		return nullptr;
	}
	if (const FPrimitiveDataLegendEntry* ById = Legend->FindParameter(Selected.Id))
	{
		return ById;
	}
	return Selected.Name.IsNone() ? nullptr : Legend->FindParameter(Selected.Name);
}

// ---------------------------------------------------------------------------
// Selection
// ---------------------------------------------------------------------------

bool UK2Node_SetNamedPrimitiveDataMulti::IsParameterSelected(const FGuid& Id) const
{
	return Selection.ContainsByPredicate([&Id](const FNamedPrimitiveDataSelection& Selected) { return Selected.Id == Id; });
}

void UK2Node_SetNamedPrimitiveDataMulti::SetParameterSelected(const FGuid& Id, bool bSelected)
{
	if (IsParameterSelected(Id) == bSelected)
	{
		return;
	}

	Modify();
	if (bSelected)
	{
		Selection.AddDefaulted_GetRef().Id = Id;
	}
	else
	{
		Selection.RemoveAll([&Id](const FNamedPrimitiveDataSelection& Selected) { return Selected.Id == Id; });
		DropValuePin(Id);
	}
	RefreshSelection(nullptr);
	Rebuild();
}

void UK2Node_SetNamedPrimitiveDataMulti::DropValuePin(const FGuid& Id)
{
	// Removed outright: left to reconstruction, a pin with a wire or a set value would be kept as an
	// orphan with a warning, which is right for a parameter that vanished but not for one unticked.
	if (UEdGraphPin* Pin = FindValuePin(Id))
	{
		Pin->BreakAllPinLinks();
		RemovePin(Pin);
	}
}

void UK2Node_SetNamedPrimitiveDataMulti::RefreshSelection(const TArray<UEdGraphPin*>* InPins)
{
	const UPrimitiveDataLegend* Legend = GetLegend(InPins);
	if (!Legend)
	{
		// Nothing to check against. Keep the selection as it is, so choosing the legend again restores it.
		return;
	}

	for (FNamedPrimitiveDataSelection& Selected : Selection)
	{
		// A selection the legend no longer has keeps its id and name, so an undo in the legend editor
		// brings it straight back. Only the kind drops, so it cannot compile against a missing type.
		const FPrimitiveDataLegendEntry* Entry = Resolve(Legend, Selected);
		if (Entry)
		{
			Selected.Id = Entry->Id;
			Selected.Name = Entry->Name;
		}
		Selected.Kind = SetNamedPrimitiveDataMulti::KindOf(Entry);
	}

	// Pins in the legend's order, whatever order they were ticked in. Missing ones go last.
	auto IndexOf = [Legend](const FNamedPrimitiveDataSelection& Selected)
	{
		const int32 Index = Legend->Parameters.IndexOfByPredicate(
			[&Selected](const FPrimitiveDataLegendEntry& Entry) { return Entry.Id == Selected.Id; });
		return Index == INDEX_NONE ? MAX_int32 : Index;
	};
	Selection.StableSort([&IndexOf](const FNamedPrimitiveDataSelection& A, const FNamedPrimitiveDataSelection& B)
	{
		return IndexOf(A) < IndexOf(B);
	});
}

void UK2Node_SetNamedPrimitiveDataMulti::Rebuild()
{
	ReconstructNode();
	if (UEdGraph* Graph = GetGraph())
	{
		Graph->NotifyNodeChanged(this);
	}
	if (UBlueprint* Blueprint = FBlueprintEditorUtils::FindBlueprintForNode(this))
	{
		FBlueprintEditorUtils::MarkBlueprintAsModified(Blueprint);
	}
}

void UK2Node_SetNamedPrimitiveDataMulti::PinDefaultValueChanged(UEdGraphPin* Pin)
{
	Super::PinDefaultValueChanged(Pin);
	if (!Pin || Pin->PinName != LegendPinName)
	{
		return;
	}

	// A new legend: keep every ticked parameter it also has (by id, or by name for a legend that shares
	// the layout), drop the rest.
	Modify();
	const UPrimitiveDataLegend* Legend = GetLegend();
	Selection.RemoveAll([this, Legend](const FNamedPrimitiveDataSelection& Selected)
	{
		if (Resolve(Legend, Selected))
		{
			return false;
		}
		DropValuePin(Selected.Id);
		return true;
	});
	RefreshSelection(nullptr);
	Rebuild();
	OnParametersOffered.Broadcast();
}

void UK2Node_SetNamedPrimitiveDataMulti::ReallocatePinsDuringReconstruction(TArray<UEdGraphPin*>& OldPins)
{
	// The new pins only get their defaults copied over after this returns: read the legend off the old ones.
	if (UPrimitiveDataLegend* Legend = GetLegend(&OldPins))
	{
		PreloadObject(Legend);
	}
	RefreshSelection(&OldPins);

	Super::ReallocatePinsDuringReconstruction(OldPins);
}

UK2Node::ERedirectType UK2Node_SetNamedPrimitiveDataMulti::DoPinsMatchForReconstruction(const UEdGraphPin* NewPin,
	int32 NewPinIndex, const UEdGraphPin* OldPin, int32 OldPinIndex) const
{
	if (NewPin && OldPin && NewPin->Direction == OldPin->Direction && NewPin->PinName == OldPin->PinName)
	{
		// A parameter whose type changed in the legend: its wire and value no longer fit, so let them go
		// rather than carry a colour into a float.
		const bool bSameType = NewPin->PinType.PinCategory == OldPin->PinType.PinCategory
			&& NewPin->PinType.PinSubCategoryObject == OldPin->PinType.PinSubCategoryObject;
		if (!bSameType)
		{
			return ERedirectType_None;
		}
	}
	return Super::DoPinsMatchForReconstruction(NewPin, NewPinIndex, OldPin, OldPinIndex);
}

void UK2Node_SetNamedPrimitiveDataMulti::PreloadRequiredAssets()
{
	if (UPrimitiveDataLegend* Legend = GetLegend())
	{
		PreloadObject(Legend);
	}
	Super::PreloadRequiredAssets();
}

bool UK2Node_SetNamedPrimitiveDataMulti::GetWriteRange(int32& OutFirst, int32& OutCount, uint64& OutMask) const
{
	OutFirst = 0;
	OutCount = 0;
	OutMask = 0;

	const UPrimitiveDataLegend* Legend = GetLegend();
	int32 First = MAX_int32;
	int32 End = 0;
	for (const FNamedPrimitiveDataSelection& Selected : Selection)
	{
		const FPrimitiveDataLegendEntry* Entry = Resolve(Legend, Selected);
		if (Entry && Entry->HasSlot())
		{
			First = FMath::Min(First, Entry->Slot);
			End = FMath::Max(End, Entry->Slot + Entry->GetWidth());
		}
	}
	if (First == MAX_int32)
	{
		return false;
	}

	for (const FNamedPrimitiveDataSelection& Selected : Selection)
	{
		const FPrimitiveDataLegendEntry* Entry = Resolve(Legend, Selected);
		if (Entry && Entry->HasSlot())
		{
			for (int32 Float = 0; Float < Entry->GetWidth(); ++Float)
			{
				OutMask |= uint64(1) << (Entry->Slot - First + Float);
			}
		}
	}
	OutFirst = First;
	OutCount = End - First;
	return true;
}

#if WITH_EDITOR
void UK2Node_SetNamedPrimitiveDataMulti::PostEditChangeProperty(FPropertyChangedEvent& Event)
{
	Super::PostEditChangeProperty(Event);
	if (Event.GetPropertyName() == GET_MEMBER_NAME_CHECKED(UK2Node_SetNamedPrimitiveDataMulti, bWriteDefaults))
	{
		// Only the title and the compiled call change; the pins stay as they are.
		if (UEdGraph* Graph = GetGraph())
		{
			Graph->NotifyNodeChanged(this);
		}
		if (UBlueprint* Blueprint = FBlueprintEditorUtils::FindBlueprintForNode(this))
		{
			FBlueprintEditorUtils::MarkBlueprintAsModified(Blueprint);
		}
	}
}
#endif

// ---------------------------------------------------------------------------
// Presentation
// ---------------------------------------------------------------------------

FText UK2Node_SetNamedPrimitiveDataMulti::GetNodeTitle(ENodeTitleType::Type TitleType) const
{
	if (TitleType == ENodeTitleType::FullTitle)
	{
		if (const UPrimitiveDataLegend* Legend = GetLegend())
		{
			return FText::Format(bWriteDefaults
					? LOCTEXT("DefaultTitleWithLegend", "Set Named Primitive Data Defaults (Multiple)\n{0}")
					: LOCTEXT("TitleWithLegend", "Set Named Primitive Data (Multiple)\n{0}"),
				FText::FromString(Legend->GetName()));
		}
	}
	return bWriteDefaults
		? LOCTEXT("DefaultTitle", "Set Named Primitive Data Defaults (Multiple)")
		: LOCTEXT("Title", "Set Named Primitive Data (Multiple)");
}

FText UK2Node_SetNamedPrimitiveDataMulti::GetTooltipText() const
{
	return LOCTEXT("Tooltip",
		"Set several custom primitive data parameters on a mesh in a single update, chosen by name from a "
		"Primitive Data Legend. Tick the parameters in the Details panel.\n\n"
		"Cheaper than one Set Named Primitive Data per parameter when done every frame on many meshes: each "
		"of those is a separate update to the renderer, this is one.\n\n"
		"Write Defaults (Details panel) sets the Custom Primitive Data Defaults instead, which are saved with the "
		"mesh - use it in construction scripts, where runtime data does not survive the level loading. It rebuilds "
		"the mesh's render state, so not every frame.");
}

FSlateIcon UK2Node_SetNamedPrimitiveDataMulti::GetIconAndTint(FLinearColor& OutColor) const
{
	static const FSlateIcon Icon(FAppStyle::GetAppStyleSetName(), TEXT("Kismet.AllClasses.FunctionIcon"));
	return Icon;
}

void UK2Node_SetNamedPrimitiveDataMulti::GetMenuActions(FBlueprintActionDatabaseRegistrar& ActionRegistrar) const
{
	UClass* ActionKey = GetClass();
	if (ActionRegistrar.IsOpenForRegistration(ActionKey))
	{
		UBlueprintNodeSpawner* Spawner = UBlueprintNodeSpawner::Create(ActionKey);
		check(Spawner);
		ActionRegistrar.AddBlueprintAction(ActionKey, Spawner);
	}
}

FText UK2Node_SetNamedPrimitiveDataMulti::GetMenuCategory() const
{
	return LOCTEXT("Category", "Rendering|Material");
}

FText UK2Node_SetNamedPrimitiveDataMulti::GetKeywords() const
{
	return LOCTEXT("Keywords", "custom primitive data cpd legend named parameter set multiple several many batch");
}

// ---------------------------------------------------------------------------
// Compilation
// ---------------------------------------------------------------------------

void UK2Node_SetNamedPrimitiveDataMulti::ValidateNodeDuringCompilation(FCompilerResultsLog& MessageLog) const
{
	Super::ValidateNodeDuringCompilation(MessageLog);

	const UPrimitiveDataLegend* Legend = GetLegend();
	if (!Legend)
	{
		MessageLog.Error(*LOCTEXT("NoLegend", "@@ has no Primitive Data Legend chosen.").ToString(), this);
		return;
	}
	if (Selection.Num() == 0)
	{
		MessageLog.Error(*LOCTEXT("NothingTicked", "@@ sets nothing - tick its parameters in the Details panel.").ToString(), this);
		return;
	}
	for (const FNamedPrimitiveDataSelection& Selected : Selection)
	{
		const FPrimitiveDataLegendEntry* Entry = Resolve(Legend, Selected);
		if (!Entry)
		{
			MessageLog.Error(*FText::Format(LOCTEXT("NoParameter", "@@: parameter '{0}' is not in {1}."),
				FText::FromName(Selected.Name), FText::FromString(Legend->GetName())).ToString(), this);
		}
		else if (!Entry->HasSlot())
		{
			MessageLog.Error(*FText::Format(
				LOCTEXT("NoSlot", "@@: '{0}' has no slot in {1} - the legend is out of room. Open it for details."),
				FText::FromName(Entry->Name), FText::FromString(Legend->GetName())).ToString(), this);
		}
		else if (SetNamedPrimitiveDataMulti::KindOf(Entry) != Selected.Kind)
		{
			MessageLog.Error(*FText::Format(
				LOCTEXT("StaleKind", "@@: '{0}' changed type in {1}. Refresh the node (right-click > Refresh Nodes)."),
				FText::FromName(Entry->Name), FText::FromString(Legend->GetName())).ToString(), this);
		}
	}
}

void UK2Node_SetNamedPrimitiveDataMulti::ExpandNode(FKismetCompilerContext& CompilerContext, UEdGraph* SourceGraph)
{
	Super::ExpandNode(CompilerContext, SourceGraph);

	const UEdGraphSchema_K2* Schema = CompilerContext.GetSchema();
	const UPrimitiveDataLegend* Legend = GetLegend();

	// Validation says why for each of these; all that is left is to emit nothing.
	struct FWrite
	{
		const FPrimitiveDataLegendEntry* Entry;
		UEdGraphPin* Pin;
	};
	TArray<FWrite> Writes;
	bool bValid = Legend != nullptr && Selection.Num() > 0;
	for (const FNamedPrimitiveDataSelection& Selected : Selection)
	{
		const FPrimitiveDataLegendEntry* Entry = Resolve(Legend, Selected);
		UEdGraphPin* Pin = FindValuePin(Selected.Id);
		if (!Entry || !Entry->HasSlot() || !Pin || SetNamedPrimitiveDataMulti::KindOf(Entry) != Selected.Kind)
		{
			bValid = false;
			break;
		}
		Writes.Add({ Entry, Pin });
	}
	int32 First = 0;
	int32 Count = 0;
	uint64 Mask = 0;
	if (!bValid || !GetWriteRange(First, Count, Mask))
	{
		BreakAllNodeLinks();
		return;
	}

	// Unwired Target means self: fine in a primitive component's own Blueprint, an error anywhere else.
	UEdGraphPin* Target = FindPinChecked(TargetPinName);
	if (Target->LinkedTo.Num() == 0)
	{
		const UClass* Context = CompilerContext.Blueprint ? CompilerContext.Blueprint->ParentClass : nullptr;
		if (!Context || !Context->IsChildOf(UPrimitiveComponent::StaticClass()))
		{
			CompilerContext.MessageLog.Error(*LOCTEXT("NoTarget", "@@ needs a mesh connected to Target.").ToString(), this);
			BreakAllNodeLinks();
			return;
		}
	}

	// Side by side, every float in the range is ours: the engine call does it alone. Otherwise the
	// floats in between have to be read back and kept, which only the plugin's function does.
	const uint64 Full = Count >= 64 ? ~uint64(0) : (uint64(1) << Count) - 1;
	const bool bContiguous = Mask == Full;

	UK2Node_CallFunction* Set = CompilerContext.SpawnIntermediateNode<UK2Node_CallFunction>(this, SourceGraph);
	if (bContiguous)
	{
		Set->FunctionReference.SetExternalMember(bWriteDefaults
			? SetNamedPrimitiveDataMulti::DefaultFloatArrayFunction
			: SetNamedPrimitiveDataMulti::FloatArrayFunction, UPrimitiveComponent::StaticClass());
	}
	else
	{
		Set->SetFromFunction(UPrimitiveDataSetLibrary::StaticClass()->FindFunctionByName(bWriteDefaults
			? GET_FUNCTION_NAME_CHECKED(UPrimitiveDataSetLibrary, SetDefaultCustomPrimitiveDataMasked)
			: GET_FUNCTION_NAME_CHECKED(UPrimitiveDataSetLibrary, SetCustomPrimitiveDataMasked)));
	}
	Set->AllocateDefaultPins();
	UEdGraphPin* ValuesInput = Set->FindPin(TEXT("Values"));
	UEdGraphPin* IndexInput = Set->FindPin(TEXT("DataIndex"));
	if (!Set->GetTargetFunction() || !ValuesInput || !IndexInput)
	{
		CompilerContext.MessageLog.Error(*LOCTEXT("MissingFunction",
			"@@: internal error - the primitive data function to call was not found.").ToString(), this);
		BreakAllNodeLinks();
		return;
	}

	CompilerContext.MovePinLinksToIntermediate(*GetExecPin(), *Set->GetExecPin());
	CompilerContext.MovePinLinksToIntermediate(*FindPinChecked(UEdGraphSchema_K2::PN_Then), *Set->GetThenPin());
	// The slot is a literal, decided now, as on the single node.
	Schema->TrySetDefaultValue(*IndexInput, FString::FromInt(First));

	bool bWired = true;

	if (bContiguous)
	{
		// A member call: its self pin takes several wires or an array and loops, as the engine's own do.
		CompilerContext.MovePinLinksToIntermediate(*Target, *Set->FindPinChecked(UEdGraphSchema_K2::PN_Self));
	}
	else
	{
		Schema->TrySetDefaultValue(*Set->FindPinChecked(TEXT("Mask")), FString::Printf(TEXT("%lld"), static_cast<int64>(Mask)));

		// A static function takes its meshes as an array: pass an array straight through, gather
		// separate wires (or self, unwired) into one. The loop happens in C++ rather than in script.
		UEdGraphPin* TargetsInput = Set->FindPinChecked(TEXT("Targets"));
		if (Target->LinkedTo.Num() == 1 && Target->LinkedTo[0]->PinType.IsArray())
		{
			CompilerContext.MovePinLinksToIntermediate(*Target, *TargetsInput);
		}
		else
		{
			TArray<UEdGraphPin*> Sources = Target->LinkedTo;
			if (Sources.ContainsByPredicate([](const UEdGraphPin* Source) { return Source->PinType.IsArray(); }))
			{
				CompilerContext.MessageLog.Error(*LOCTEXT("MixedTargets",
					"@@: Target takes one array, or any number of single meshes, but not both.").ToString(), this);
				BreakAllNodeLinks();
				return;
			}
			if (Sources.Num() == 0)
			{
				UK2Node_Self* Self = CompilerContext.SpawnIntermediateNode<UK2Node_Self>(this, SourceGraph);
				Self->AllocateDefaultPins();
				Sources.Add(Self->FindPinChecked(UEdGraphSchema_K2::PN_Self));
			}
			Target->BreakAllPinLinks();

			UK2Node_MakeArray* Meshes = CompilerContext.SpawnIntermediateNode<UK2Node_MakeArray>(this, SourceGraph);
			Meshes->AllocateDefaultPins();
			bWired &= Schema->TryCreateConnection(Meshes->GetOutputPin(), TargetsInput);
			Meshes->PinConnectionListChanged(Meshes->GetOutputPin());
			for (int32 Index = 0; Index < Sources.Num(); ++Index)
			{
				if (Index > 0)
				{
					Meshes->AddInputPin();
				}
				bWired &= Schema->TryCreateConnection(Sources[Index], Meshes->FindPinChecked(Meshes->GetPinName(Index)));
			}
		}
	}

	// Every float in the range, in order. Gaps between parameters are left at zero: the masked function
	// never writes them.
	UK2Node_MakeArray* Values = CompilerContext.SpawnIntermediateNode<UK2Node_MakeArray>(this, SourceGraph);
	Values->AllocateDefaultPins();
	bWired &= Schema->TryCreateConnection(Values->GetOutputPin(), ValuesInput);
	Values->PinConnectionListChanged(Values->GetOutputPin());
	for (int32 Index = 1; Index < Count; ++Index)
	{
		Values->AddInputPin();
	}
	auto Element = [Values](int32 Index) { return Values->FindPinChecked(Values->GetPinName(Index)); };

	for (const FWrite& Write : Writes)
	{
		const int32 Offset = Write.Entry->Slot - First;
		if (Write.Entry->GetWidth() == 1)
		{
			// Moves the default too, when nothing is connected.
			bWired &= CompilerContext.MovePinLinksToIntermediate(*Write.Pin, *Element(Offset)).CanSafeConnect();
			continue;
		}

		// FLinearColor -> four floats, with an engine function so the cooked graph needs nothing else.
		UK2Node_CallFunction* Break = CompilerContext.SpawnIntermediateNode<UK2Node_CallFunction>(this, SourceGraph);
		Break->FunctionReference.SetExternalMember(GET_FUNCTION_NAME_CHECKED(UKismetMathLibrary, BreakColor), UKismetMathLibrary::StaticClass());
		Break->AllocateDefaultPins();
		bWired &= CompilerContext.MovePinLinksToIntermediate(*Write.Pin, *Break->FindPinChecked(TEXT("InColor"))).CanSafeConnect();
		const TCHAR* Channels[] = { TEXT("R"), TEXT("G"), TEXT("B"), TEXT("A") };
		for (int32 Channel = 0; Channel < 4; ++Channel)
		{
			bWired &= Schema->TryCreateConnection(Break->FindPinChecked(Channels[Channel]), Element(Offset + Channel));
		}
	}

	if (!bWired)
	{
		CompilerContext.MessageLog.Error(*LOCTEXT("WireFailed", "@@: internal error wiring the primitive data write.").ToString(), this);
	}
	BreakAllNodeLinks();
}

#undef LOCTEXT_NAMESPACE
