#include "K2Node_SetIndexedPrimitiveData.h"

#include "BlueprintActionDatabaseRegistrar.h"
#include "BlueprintNodeSpawner.h"
#include "Components/PrimitiveComponent.h"
#include "EdGraphSchema_K2.h"
#include "K2Node_CallFunction.h"
#include "Kismet/KismetMathLibrary.h"
#include "Kismet2/BlueprintEditorUtils.h"
#include "Kismet2/CompilerResultsLog.h"
#include "KismetCompiler.h"
#include "Styling/AppStyle.h"

#define LOCTEXT_NAMESPACE "K2Node_SetIndexedPrimitiveData"

// A SELF pin, not a plain object pin named Target: the schema only lets an array or several wires into
// a pin that is self, and only then on a node answering AllowMultipleSelfs. Shown as "Target", as the
// engine's own function nodes show theirs.
const FName UK2Node_SetIndexedPrimitiveData::TargetPinName(UEdGraphSchema_K2::PN_Self);
const FName UK2Node_SetIndexedPrimitiveData::IndexPinName(TEXT("Index"));
const FName UK2Node_SetIndexedPrimitiveData::ParameterPinName(TEXT("Parameter"));
const FName UK2Node_SetIndexedPrimitiveData::ValuePinName(TEXT("Value"));

namespace SetIndexedPrimitiveData
{
	/** White, opaque. A colour pin arriving as transparent black would read as "nothing happened". */
	const TCHAR* DefaultColor = TEXT("(R=1.000000,G=1.000000,B=1.000000,A=1.000000)");
	const TCHAR* DefaultScalar = TEXT("0.0");
}

// ---------------------------------------------------------------------------
// Pins
// ---------------------------------------------------------------------------

void UK2Node_SetIndexedPrimitiveData::AllocateDefaultPins()
{
	CreatePin(EGPD_Input, UEdGraphSchema_K2::PC_Exec, UEdGraphSchema_K2::PN_Execute);
	CreatePin(EGPD_Output, UEdGraphSchema_K2::PC_Exec, UEdGraphSchema_K2::PN_Then);

	UEdGraphPin* Target = CreatePin(EGPD_Input, UEdGraphSchema_K2::PC_Object, UPrimitiveComponent::StaticClass(), TargetPinName);
	Target->PinFriendlyName = LOCTEXT("TargetName", "Target");
	Target->PinToolTip = LOCTEXT("TargetTooltip",
		"The mesh (any primitive component) to set the data on. Wire in several, or an array, to set it on each.").ToString();

	// Choices made on the node, not data - see the class comment. bNotConnectable leaves only the
	// default-value widget: the asset picker here, the parameter dropdown on the next pin.
	UEdGraphPin* Index = CreatePin(EGPD_Input, UEdGraphSchema_K2::PC_Object, UPrimitiveDataIndex::StaticClass(), IndexPinName);
	Index->bNotConnectable = true;
	Index->PinToolTip = LOCTEXT("IndexTooltip", "The Primitive Data Index that names the parameters.").ToString();

	UEdGraphPin* Parameter = CreatePin(EGPD_Input, UEdGraphSchema_K2::PC_Name, ParameterPinName);
	Parameter->bNotConnectable = true;
	Parameter->PinToolTip = LOCTEXT("ParameterTooltip", "Which of the index's parameters to set.").ToString();

	CreateValuePin();

	Super::AllocateDefaultPins();
}

void UK2Node_SetIndexedPrimitiveData::CreateValuePin()
{
	UEdGraphPin* Value = nullptr;
	switch (ValueKind)
	{
	case EIndexedPrimitiveDataValueKind::Scalar:
		Value = CreatePin(EGPD_Input, UEdGraphSchema_K2::PC_Real, UEdGraphSchema_K2::PC_Float, ValuePinName);
		GetDefault<UEdGraphSchema_K2>()->SetPinAutogeneratedDefaultValue(Value, SetIndexedPrimitiveData::DefaultScalar);
		break;
	case EIndexedPrimitiveDataValueKind::Vector:
		Value = CreatePin(EGPD_Input, UEdGraphSchema_K2::PC_Struct, TBaseStructure<FLinearColor>::Get(), ValuePinName);
		GetDefault<UEdGraphSchema_K2>()->SetPinAutogeneratedDefaultValue(Value, SetIndexedPrimitiveData::DefaultColor);
		break;
	default:
		// No parameter chosen: no Value pin at all, rather than a wildcard that would accept anything
		// and then fail to compile.
		break;
	}
}

UEdGraphPin* UK2Node_SetIndexedPrimitiveData::FindPinIn(FName Name, const TArray<UEdGraphPin*>* InPins) const
{
	const TArray<UEdGraphPin*>& Search = InPins ? *InPins : Pins;
	for (UEdGraphPin* Pin : Search)
	{
		if (Pin && Pin->PinName == Name)
		{
			return Pin;
		}
	}
	return nullptr;
}

UPrimitiveDataIndex* UK2Node_SetIndexedPrimitiveData::GetIndex(const TArray<UEdGraphPin*>* InPins) const
{
	const UEdGraphPin* Pin = FindPinIn(IndexPinName, InPins);
	return Pin ? Cast<UPrimitiveDataIndex>(Pin->DefaultObject) : nullptr;
}

const FPrimitiveDataIndexEntry* UK2Node_SetIndexedPrimitiveData::ResolveParameter(const TArray<UEdGraphPin*>* InPins) const
{
	const UPrimitiveDataIndex* Index = GetIndex(InPins);
	if (!Index)
	{
		return nullptr;
	}
	if (const FPrimitiveDataIndexEntry* ById = Index->FindParameter(ParameterId))
	{
		return ById;
	}
	const UEdGraphPin* Pin = FindPinIn(ParameterPinName, InPins);
	return Pin ? Index->FindParameter(FName(*Pin->DefaultValue)) : nullptr;
}

EIndexedPrimitiveDataValueKind UK2Node_SetIndexedPrimitiveData::KindOf(const FPrimitiveDataIndexEntry* Entry)
{
	if (!Entry)
	{
		return EIndexedPrimitiveDataValueKind::None;
	}
	return Entry->Type == EPrimitiveDataParameterType::Vector
		? EIndexedPrimitiveDataValueKind::Vector
		: EIndexedPrimitiveDataValueKind::Scalar;
}

void UK2Node_SetIndexedPrimitiveData::RefreshSelection(const TArray<UEdGraphPin*>* InPins)
{
	const FPrimitiveDataIndexEntry* Entry = ResolveParameter(InPins);
	if (Entry)
	{
		ParameterId = Entry->Id;
		ParameterName = Entry->Name;
	}
	// A selection the index no longer has keeps its GUID: if the entry comes back (an undo in the
	// index editor) the node picks it straight up again. The kind still has to drop, so the node
	// cannot compile against a type that is no longer there.
	ValueKind = KindOf(Entry);
}

void UK2Node_SetIndexedPrimitiveData::SetValueKind(EIndexedPrimitiveDataValueKind NewKind)
{
	if (NewKind == ValueKind)
	{
		return;
	}

	Modify();
	if (UEdGraphPin* Old = FindPin(ValuePinName))
	{
		Old->BreakAllPinLinks();
		RemovePin(Old);
	}
	ValueKind = NewKind;
	CreateValuePin();

	if (UEdGraph* Graph = GetGraph())
	{
		Graph->NotifyNodeChanged(this);
	}
	if (UBlueprint* Blueprint = FBlueprintEditorUtils::FindBlueprintForNode(this))
	{
		FBlueprintEditorUtils::MarkBlueprintAsModified(Blueprint);
	}
}

void UK2Node_SetIndexedPrimitiveData::PinDefaultValueChanged(UEdGraphPin* Pin)
{
	Super::PinDefaultValueChanged(Pin);
	if (!Pin)
	{
		return;
	}

	if (Pin->PinName == IndexPinName)
	{
		Modify();

		// A new index: keep the current parameter if the new index has it too (swapping between two
		// indexes that share a layout should not lose the choice), otherwise take the first one, so
		// the node is immediately usable rather than showing an empty dropdown.
		const UPrimitiveDataIndex* Index = GetIndex();
		const FPrimitiveDataIndexEntry* Entry = ResolveParameter();
		if (!Entry && Index && Index->Parameters.Num() > 0)
		{
			Entry = &Index->Parameters[0];
		}

		ParameterId = Entry ? Entry->Id : FGuid();
		ParameterName = Entry ? Entry->Name : NAME_None;
		if (UEdGraphPin* ParameterPin = FindPin(ParameterPinName))
		{
			ParameterPin->DefaultValue = ParameterName.IsNone() ? FString() : ParameterName.ToString();
		}
		SetValueKind(KindOf(Entry));
	}
	else if (Pin->PinName == ParameterPinName)
	{
		Modify();
		const UPrimitiveDataIndex* Index = GetIndex();
		const FPrimitiveDataIndexEntry* Entry = Index ? Index->FindParameter(FName(*Pin->DefaultValue)) : nullptr;
		ParameterId = Entry ? Entry->Id : FGuid();
		ParameterName = Entry ? Entry->Name : NAME_None;
		SetValueKind(KindOf(Entry));
	}
}

void UK2Node_SetIndexedPrimitiveData::ReallocatePinsDuringReconstruction(TArray<UEdGraphPin*>& OldPins)
{
	// The new pins get their defaults copied over only AFTER this returns, so the index has to be read
	// off the old ones - and loaded, since reconstruction can run while the Blueprint itself is loading.
	if (UPrimitiveDataIndex* Index = GetIndex(&OldPins))
	{
		PreloadObject(Index);
	}
	RefreshSelection(&OldPins);

	Super::ReallocatePinsDuringReconstruction(OldPins);
}

void UK2Node_SetIndexedPrimitiveData::PostReconstructNode()
{
	Super::PostReconstructNode();

	// Reconstruction copied the OLD name back onto the pin. If the parameter was relabelled in the
	// index since, the GUID found it under its new name; show that one.
	if (!ParameterName.IsNone())
	{
		if (UEdGraphPin* ParameterPin = FindPin(ParameterPinName))
		{
			ParameterPin->DefaultValue = ParameterName.ToString();
		}
	}
}

UK2Node::ERedirectType UK2Node_SetIndexedPrimitiveData::DoPinsMatchForReconstruction(const UEdGraphPin* NewPin,
	int32 NewPinIndex, const UEdGraphPin* OldPin, int32 OldPinIndex) const
{
	static const FName LegacyTargetPinName(TEXT("Target"));
	if (NewPin && OldPin && NewPin->PinName == TargetPinName && OldPin->PinName == LegacyTargetPinName
		&& NewPin->Direction == OldPin->Direction)
	{
		return ERedirectType_Name;
	}
	return Super::DoPinsMatchForReconstruction(NewPin, NewPinIndex, OldPin, OldPinIndex);
}

void UK2Node_SetIndexedPrimitiveData::PreloadRequiredAssets()
{
	// Blueprints compile on load in the editor; ExpandNode reads the index, so it has to be in memory.
	if (UPrimitiveDataIndex* Index = GetIndex())
	{
		PreloadObject(Index);
	}
	Super::PreloadRequiredAssets();
}

// ---------------------------------------------------------------------------
// Presentation
// ---------------------------------------------------------------------------

FText UK2Node_SetIndexedPrimitiveData::GetNodeTitle(ENodeTitleType::Type TitleType) const
{
	if (TitleType == ENodeTitleType::FullTitle && !ParameterName.IsNone())
	{
		if (const UPrimitiveDataIndex* Index = GetIndex())
		{
			// Second line is the index, the way a function node shows its target class.
			return FText::Format(LOCTEXT("TitleWithParameter", "Set {0}\n{1}"),
				FText::FromName(ParameterName), FText::FromString(Index->GetName()));
		}
	}
	return LOCTEXT("Title", "Set Indexed Primitive Data");
}

FText UK2Node_SetIndexedPrimitiveData::GetTooltipText() const
{
	return LOCTEXT("Tooltip",
		"Set one custom primitive data parameter on a mesh, chosen by name from a Primitive Data Index.\n\n"
		"Compiles to SetCustomPrimitiveDataFloat / SetCustomPrimitiveDataVector4 with the slot baked in, "
		"so it costs the same as the hand-wired call.");
}

FSlateIcon UK2Node_SetIndexedPrimitiveData::GetIconAndTint(FLinearColor& OutColor) const
{
	static const FSlateIcon Icon(FAppStyle::GetAppStyleSetName(), TEXT("Kismet.AllClasses.FunctionIcon"));
	return Icon;
}

void UK2Node_SetIndexedPrimitiveData::GetMenuActions(FBlueprintActionDatabaseRegistrar& ActionRegistrar) const
{
	UClass* ActionKey = GetClass();
	if (ActionRegistrar.IsOpenForRegistration(ActionKey))
	{
		UBlueprintNodeSpawner* Spawner = UBlueprintNodeSpawner::Create(ActionKey);
		check(Spawner);
		ActionRegistrar.AddBlueprintAction(ActionKey, Spawner);
	}
}

FText UK2Node_SetIndexedPrimitiveData::GetMenuCategory() const
{
	// Beside the engine's own SetCustomPrimitiveData* functions.
	return LOCTEXT("Category", "Rendering|Material");
}

FText UK2Node_SetIndexedPrimitiveData::GetKeywords() const
{
	return LOCTEXT("Keywords", "custom primitive data cpd index parameter set");
}

// ---------------------------------------------------------------------------
// Compilation
// ---------------------------------------------------------------------------

void UK2Node_SetIndexedPrimitiveData::ValidateNodeDuringCompilation(FCompilerResultsLog& MessageLog) const
{
	Super::ValidateNodeDuringCompilation(MessageLog);

	const UPrimitiveDataIndex* Index = GetIndex();
	if (!Index)
	{
		MessageLog.Error(*LOCTEXT("NoIndex", "@@ has no Primitive Data Index chosen.").ToString(), this);
		return;
	}

	const FPrimitiveDataIndexEntry* Entry = ResolveParameter();
	if (!Entry)
	{
		MessageLog.Error(*FText::Format(
			LOCTEXT("NoParameter", "@@: parameter '{0}' is not in {1}."),
			FText::FromName(ParameterName), FText::FromString(Index->GetName())).ToString(), this);
		return;
	}
	if (!Entry->HasSlot())
	{
		MessageLog.Error(*FText::Format(
			LOCTEXT("NoSlot", "@@: '{0}' has no slot in {1} - the index is out of room. Open it for details."),
			FText::FromName(Entry->Name), FText::FromString(Index->GetName())).ToString(), this);
		return;
	}
	if (KindOf(Entry) != ValueKind)
	{
		MessageLog.Error(*FText::Format(
			LOCTEXT("StaleKind", "@@: '{0}' changed type in {1}. Refresh the node (right-click > Refresh Nodes)."),
			FText::FromName(Entry->Name), FText::FromString(Index->GetName())).ToString(), this);
		return;
	}

	// NOT checked here: whether Target is connected. The compiler validates AFTER expansion, by which
	// point ExpandNode has handed every link to the intermediate call and this node has none - so a
	// link check here fails on every correctly wired node. It lives in ExpandNode, before the move.
}

void UK2Node_SetIndexedPrimitiveData::ExpandNode(FKismetCompilerContext& CompilerContext, UEdGraph* SourceGraph)
{
	Super::ExpandNode(CompilerContext, SourceGraph);

	const UEdGraphSchema_K2* Schema = CompilerContext.GetSchema();
	const FPrimitiveDataIndexEntry* Entry = ResolveParameter();
	UEdGraphPin* Value = FindPin(ValuePinName);

	// ValidateNodeDuringCompilation has already said why; all that is left is to not emit anything.
	if (!Entry || !Entry->HasSlot() || !Value || KindOf(Entry) != ValueKind)
	{
		BreakAllNodeLinks();
		return;
	}

	// Unwired Target means "self", as on any engine node - fine when this Blueprint IS a primitive
	// component, an error anywhere else. Checked here rather than left to the intermediate call so the
	// message names this node, not a node the user never placed.
	UEdGraphPin* Target = FindPinChecked(TargetPinName);
	if (Target->LinkedTo.Num() == 0)
	{
		const UClass* Context = CompilerContext.Blueprint ? CompilerContext.Blueprint->ParentClass : nullptr;
		if (!Context || !Context->IsChildOf(UPrimitiveComponent::StaticClass()))
		{
			CompilerContext.MessageLog.Error(*LOCTEXT("NoTarget", "@@ needs a mesh connected to Target.").ToString(), this);
			BreakAllNodeLinks();
			return;
		}
	}

	const bool bVector = (ValueKind == EIndexedPrimitiveDataValueKind::Vector);

	UK2Node_CallFunction* Set = CompilerContext.SpawnIntermediateNode<UK2Node_CallFunction>(this, SourceGraph);
	Set->FunctionReference.SetExternalMember(bVector
		? GET_FUNCTION_NAME_CHECKED(UPrimitiveComponent, SetCustomPrimitiveDataVector4)
		: GET_FUNCTION_NAME_CHECKED(UPrimitiveComponent, SetCustomPrimitiveDataFloat),
		UPrimitiveComponent::StaticClass());
	Set->AllocateDefaultPins();

	CompilerContext.MovePinLinksToIntermediate(*GetExecPin(), *Set->GetExecPin());
	CompilerContext.MovePinLinksToIntermediate(*FindPinChecked(UEdGraphSchema_K2::PN_Then), *Set->GetThenPin());
	CompilerContext.MovePinLinksToIntermediate(*Target, *Set->FindPinChecked(UEdGraphSchema_K2::PN_Self));

	// THE point of the node: the slot is a literal, decided now, never looked up at runtime.
	Schema->TrySetDefaultValue(*Set->FindPinChecked(TEXT("DataIndex")), FString::FromInt(Entry->Slot));

	if (!bVector)
	{
		CompilerContext.MovePinLinksToIntermediate(*Value, *Set->FindPinChecked(TEXT("Value")));
	}
	else
	{
		// FLinearColor -> FVector4. The engine has no single conversion for this, so it is BreakColor
		// into MakeVector4: both are engine functions, which keeps the cooked Blueprint free of any
		// dependency on this plugin.
		UK2Node_CallFunction* Break = CompilerContext.SpawnIntermediateNode<UK2Node_CallFunction>(this, SourceGraph);
		Break->FunctionReference.SetExternalMember(
			GET_FUNCTION_NAME_CHECKED(UKismetMathLibrary, BreakColor), UKismetMathLibrary::StaticClass());
		Break->AllocateDefaultPins();

		UK2Node_CallFunction* Make = CompilerContext.SpawnIntermediateNode<UK2Node_CallFunction>(this, SourceGraph);
		Make->FunctionReference.SetExternalMember(
			GET_FUNCTION_NAME_CHECKED(UKismetMathLibrary, MakeVector4), UKismetMathLibrary::StaticClass());
		Make->AllocateDefaultPins();

		// Moves the default colour too, when nothing is connected.
		CompilerContext.MovePinLinksToIntermediate(*Value, *Break->FindPinChecked(TEXT("InColor")));

		const TPair<const TCHAR*, const TCHAR*> Channels[] = {
			{ TEXT("R"), TEXT("X") }, { TEXT("G"), TEXT("Y") }, { TEXT("B"), TEXT("Z") }, { TEXT("A"), TEXT("W") } };
		bool bWired = true;
		for (const TPair<const TCHAR*, const TCHAR*>& Channel : Channels)
		{
			bWired &= Schema->TryCreateConnection(Break->FindPinChecked(Channel.Key), Make->FindPinChecked(Channel.Value));
		}
		bWired &= Schema->TryCreateConnection(Make->GetReturnValuePin(), Set->FindPinChecked(TEXT("Value")));

		if (!bWired)
		{
			CompilerContext.MessageLog.Error(
				*LOCTEXT("WireFailed", "@@: internal error converting the colour for SetCustomPrimitiveDataVector4.").ToString(), this);
		}
	}

	BreakAllNodeLinks();
}

#undef LOCTEXT_NAMESPACE
