#include "K2Node_SetNamedPrimitiveData.h"

#include "BlueprintActionDatabaseRegistrar.h"
#include "BlueprintNodeSpawner.h"
#include "Components/PrimitiveComponent.h"
#include "EdGraphSchema_K2.h"
#include "K2Node_CallFunction.h"
#include "Kismet/KismetMathLibrary.h"
#include "Kismet2/BlueprintEditorUtils.h"
#include "Kismet2/CompilerResultsLog.h"
#include "KismetCompiler.h"
#include "Styling/AppStyle.h"

#define LOCTEXT_NAMESPACE "K2Node_SetNamedPrimitiveData"

// A SELF pin, not a plain object pin named Target: the schema only lets an array or several wires into
// a pin that is self, and only then on a node answering AllowMultipleSelfs. Shown as "Target", as the
// engine's own function nodes show theirs.
const FName UK2Node_SetNamedPrimitiveData::TargetPinName(UEdGraphSchema_K2::PN_Self);
const FName UK2Node_SetNamedPrimitiveData::LegendPinName(TEXT("Legend"));
const FName UK2Node_SetNamedPrimitiveData::ParameterPinName(TEXT("Parameter"));
const FName UK2Node_SetNamedPrimitiveData::ValuePinName(TEXT("Value"));

namespace SetNamedPrimitiveDataLegacy
{
	/**
	 * Pin names from before the rename (Primitive Data Index -> Legend, 2026-09-28) and before Target
	 * became a self pin. Blueprints saved with them still load: reconstruction maps them onto the new
	 * pins, and GetLegend reads the old one directly on a node not yet reconstructed.
	 */
	const FName IndexPinName(TEXT("Index"));
	const FName TargetPinName(TEXT("Target"));
}

namespace SetNamedPrimitiveData
{
	/** White, opaque. A colour pin arriving as transparent black would read as "nothing happened". */
	const TCHAR* DefaultColor = TEXT("(R=1.000000,G=1.000000,B=1.000000,A=1.000000)");
	const TCHAR* DefaultScalar = TEXT("0.0");
}

// ---------------------------------------------------------------------------
// Pins
// ---------------------------------------------------------------------------

void UK2Node_SetNamedPrimitiveData::AllocateDefaultPins()
{
	CreatePin(EGPD_Input, UEdGraphSchema_K2::PC_Exec, UEdGraphSchema_K2::PN_Execute);
	CreatePin(EGPD_Output, UEdGraphSchema_K2::PC_Exec, UEdGraphSchema_K2::PN_Then);

	UEdGraphPin* Target = CreatePin(EGPD_Input, UEdGraphSchema_K2::PC_Object, UPrimitiveComponent::StaticClass(), TargetPinName);
	Target->PinFriendlyName = LOCTEXT("TargetName", "Target");
	Target->PinToolTip = LOCTEXT("TargetTooltip",
		"The mesh (any primitive component) to set the data on. Wire in several, or an array, to set it on each.").ToString();

	// Choices made on the node, not data - see the class comment. bNotConnectable leaves only the
	// default-value widget: the asset picker here, the parameter dropdown on the next pin.
	UEdGraphPin* Legend = CreatePin(EGPD_Input, UEdGraphSchema_K2::PC_Object, UPrimitiveDataLegend::StaticClass(), LegendPinName);
	Legend->bNotConnectable = true;
	Legend->PinToolTip = LOCTEXT("LegendTooltip", "The Primitive Data Legend that names the parameters.").ToString();

	UEdGraphPin* Parameter = CreatePin(EGPD_Input, UEdGraphSchema_K2::PC_Name, ParameterPinName);
	Parameter->bNotConnectable = true;
	Parameter->PinToolTip = LOCTEXT("ParameterTooltip", "Which of the legend's parameters to set.").ToString();

	CreateValuePin();

	Super::AllocateDefaultPins();
}

void UK2Node_SetNamedPrimitiveData::CreateValuePin()
{
	UEdGraphPin* Value = nullptr;
	switch (ValueKind)
	{
	case ENamedPrimitiveDataValueKind::Scalar:
		Value = CreatePin(EGPD_Input, UEdGraphSchema_K2::PC_Real, UEdGraphSchema_K2::PC_Float, ValuePinName);
		GetDefault<UEdGraphSchema_K2>()->SetPinAutogeneratedDefaultValue(Value, SetNamedPrimitiveData::DefaultScalar);
		break;
	case ENamedPrimitiveDataValueKind::Vector:
		Value = CreatePin(EGPD_Input, UEdGraphSchema_K2::PC_Struct, TBaseStructure<FLinearColor>::Get(), ValuePinName);
		GetDefault<UEdGraphSchema_K2>()->SetPinAutogeneratedDefaultValue(Value, SetNamedPrimitiveData::DefaultColor);
		break;
	default:
		// No parameter chosen: no Value pin at all, rather than a wildcard that would accept anything
		// and then fail to compile.
		break;
	}
}

UEdGraphPin* UK2Node_SetNamedPrimitiveData::FindPinIn(FName Name, const TArray<UEdGraphPin*>* InPins) const
{
	const TArray<UEdGraphPin*>& Search = InPins ? *InPins : Pins;
	for (UEdGraphPin* Pin : Search)
	{
		if (Pin && Pin->PinName == Name)
		{
			return Pin;
		}
	}
	return nullptr;
}

UPrimitiveDataLegend* UK2Node_SetNamedPrimitiveData::GetLegend(const TArray<UEdGraphPin*>* InPins) const
{
	const UEdGraphPin* Pin = FindPinIn(LegendPinName, InPins);
	if (!Pin)
	{
		// A node saved before the rename, not yet reconstructed - notably while its Blueprint compiles
		// on load, and during reconstruction itself, where InPins are the old pins.
		Pin = FindPinIn(SetNamedPrimitiveDataLegacy::IndexPinName, InPins);
	}
	return Pin ? Cast<UPrimitiveDataLegend>(Pin->DefaultObject) : nullptr;
}

const FPrimitiveDataLegendEntry* UK2Node_SetNamedPrimitiveData::ResolveParameter(const TArray<UEdGraphPin*>* InPins) const
{
	const UPrimitiveDataLegend* Legend = GetLegend(InPins);
	if (!Legend)
	{
		return nullptr;
	}
	if (const FPrimitiveDataLegendEntry* ById = Legend->FindParameter(ParameterId))
	{
		return ById;
	}
	const UEdGraphPin* Pin = FindPinIn(ParameterPinName, InPins);
	return Pin ? Legend->FindParameter(FName(*Pin->DefaultValue)) : nullptr;
}

ENamedPrimitiveDataValueKind UK2Node_SetNamedPrimitiveData::KindOf(const FPrimitiveDataLegendEntry* Entry)
{
	if (!Entry)
	{
		return ENamedPrimitiveDataValueKind::None;
	}
	return Entry->Type == EPrimitiveDataParameterType::Vector
		? ENamedPrimitiveDataValueKind::Vector
		: ENamedPrimitiveDataValueKind::Scalar;
}

void UK2Node_SetNamedPrimitiveData::RefreshSelection(const TArray<UEdGraphPin*>* InPins)
{
	const FPrimitiveDataLegendEntry* Entry = ResolveParameter(InPins);
	if (Entry)
	{
		ParameterId = Entry->Id;
		ParameterName = Entry->Name;
	}
	// A selection the legend no longer has keeps its GUID: if the entry comes back (an undo in the
	// legend editor) the node picks it straight up again. The kind still has to drop, so the node
	// cannot compile against a type that is no longer there.
	ValueKind = KindOf(Entry);
}

void UK2Node_SetNamedPrimitiveData::SetValueKind(ENamedPrimitiveDataValueKind NewKind)
{
	if (NewKind == ValueKind)
	{
		return;
	}

	Modify();
	if (UEdGraphPin* Old = FindPin(ValuePinName))
	{
		Old->BreakAllPinLinks();
		RemovePin(Old);
	}
	ValueKind = NewKind;
	CreateValuePin();

	if (UEdGraph* Graph = GetGraph())
	{
		Graph->NotifyNodeChanged(this);
	}
	if (UBlueprint* Blueprint = FBlueprintEditorUtils::FindBlueprintForNode(this))
	{
		FBlueprintEditorUtils::MarkBlueprintAsModified(Blueprint);
	}
}

void UK2Node_SetNamedPrimitiveData::PinDefaultValueChanged(UEdGraphPin* Pin)
{
	Super::PinDefaultValueChanged(Pin);
	if (!Pin)
	{
		return;
	}

	if (Pin->PinName == LegendPinName)
	{
		Modify();

		// A new legend: keep the current parameter if the new legend has it too (swapping between two
		// legends that share a layout should not lose the choice), otherwise take the first one, so
		// the node is immediately usable rather than showing an empty dropdown.
		const UPrimitiveDataLegend* Legend = GetLegend();
		const FPrimitiveDataLegendEntry* Entry = ResolveParameter();
		if (!Entry && Legend && Legend->Parameters.Num() > 0)
		{
			Entry = &Legend->Parameters[0];
		}

		ParameterId = Entry ? Entry->Id : FGuid();
		ParameterName = Entry ? Entry->Name : NAME_None;
		if (UEdGraphPin* ParameterPin = FindPin(ParameterPinName))
		{
			ParameterPin->DefaultValue = ParameterName.IsNone() ? FString() : ParameterName.ToString();
		}
		SetValueKind(KindOf(Entry));
	}
	else if (Pin->PinName == ParameterPinName)
	{
		Modify();
		const UPrimitiveDataLegend* Legend = GetLegend();
		const FPrimitiveDataLegendEntry* Entry = Legend ? Legend->FindParameter(FName(*Pin->DefaultValue)) : nullptr;
		ParameterId = Entry ? Entry->Id : FGuid();
		ParameterName = Entry ? Entry->Name : NAME_None;
		SetValueKind(KindOf(Entry));
	}
}

void UK2Node_SetNamedPrimitiveData::ReallocatePinsDuringReconstruction(TArray<UEdGraphPin*>& OldPins)
{
	// The new pins get their defaults copied over only AFTER this returns, so the legend has to be read
	// off the old ones - and loaded, since reconstruction can run while the Blueprint itself is loading.
	if (UPrimitiveDataLegend* Legend = GetLegend(&OldPins))
	{
		PreloadObject(Legend);
	}
	RefreshSelection(&OldPins);

	Super::ReallocatePinsDuringReconstruction(OldPins);
}

void UK2Node_SetNamedPrimitiveData::PostReconstructNode()
{
	Super::PostReconstructNode();

	// Reconstruction copied the OLD name back onto the pin. If the parameter was relabelled in the
	// legend since, the GUID found it under its new name; show that one.
	if (!ParameterName.IsNone())
	{
		if (UEdGraphPin* ParameterPin = FindPin(ParameterPinName))
		{
			ParameterPin->DefaultValue = ParameterName.ToString();
		}
	}
}

UK2Node::ERedirectType UK2Node_SetNamedPrimitiveData::DoPinsMatchForReconstruction(const UEdGraphPin* NewPin,
	int32 NewPinIndex, const UEdGraphPin* OldPin, int32 OldPinIndex) const
{
	if (NewPin && OldPin && NewPin->Direction == OldPin->Direction)
	{
		const bool bTarget = NewPin->PinName == TargetPinName && OldPin->PinName == SetNamedPrimitiveDataLegacy::TargetPinName;
		const bool bLegend = NewPin->PinName == LegendPinName && OldPin->PinName == SetNamedPrimitiveDataLegacy::IndexPinName;
		if (bTarget || bLegend)
		{
			return ERedirectType_Name;
		}
	}
	return Super::DoPinsMatchForReconstruction(NewPin, NewPinIndex, OldPin, OldPinIndex);
}

void UK2Node_SetNamedPrimitiveData::PreloadRequiredAssets()
{
	// Blueprints compile on load in the editor; ExpandNode reads the legend, so it has to be in memory.
	if (UPrimitiveDataLegend* Legend = GetLegend())
	{
		PreloadObject(Legend);
	}
	Super::PreloadRequiredAssets();
}

#if WITH_EDITOR
void UK2Node_SetNamedPrimitiveData::PostEditChangeProperty(FPropertyChangedEvent& Event)
{
	Super::PostEditChangeProperty(Event);
	if (Event.GetPropertyName() == GET_MEMBER_NAME_CHECKED(UK2Node_SetNamedPrimitiveData, bWriteDefaults))
	{
		// Only the title and the compiled call change; the pins stay as they are.
		if (UEdGraph* Graph = GetGraph())
		{
			Graph->NotifyNodeChanged(this);
		}
		if (UBlueprint* Blueprint = FBlueprintEditorUtils::FindBlueprintForNode(this))
		{
			FBlueprintEditorUtils::MarkBlueprintAsModified(Blueprint);
		}
	}
}
#endif

// ---------------------------------------------------------------------------
// Presentation
// ---------------------------------------------------------------------------

FText UK2Node_SetNamedPrimitiveData::GetNodeTitle(ENodeTitleType::Type TitleType) const
{
	if (TitleType == ENodeTitleType::FullTitle && !ParameterName.IsNone())
	{
		if (const UPrimitiveDataLegend* Legend = GetLegend())
		{
			// Second line is the legend, the way a function node shows its target class.
			return FText::Format(bWriteDefaults
					? LOCTEXT("DefaultTitleWithParameter", "Set Default {0}\n{1}")
					: LOCTEXT("TitleWithParameter", "Set {0}\n{1}"),
				FText::FromName(ParameterName), FText::FromString(Legend->GetName()));
		}
	}
	return bWriteDefaults ? LOCTEXT("DefaultTitle", "Set Named Primitive Data Defaults") : LOCTEXT("Title", "Set Named Primitive Data");
}

FText UK2Node_SetNamedPrimitiveData::GetTooltipText() const
{
	return LOCTEXT("Tooltip",
		"Set one custom primitive data parameter on a mesh, chosen by name from a Primitive Data Legend.\n\n"
		"Compiles to SetCustomPrimitiveDataFloat / SetCustomPrimitiveDataVector4 with the slot baked in, "
		"so it costs the same as the hand-wired call.\n\n"
		"Write Defaults (Details panel) sets the Custom Primitive Data Defaults instead, which are saved with the "
		"mesh - use it in construction scripts, where runtime data does not survive the level loading. It rebuilds "
		"the mesh's render state, so not every frame.");
}

FSlateIcon UK2Node_SetNamedPrimitiveData::GetIconAndTint(FLinearColor& OutColor) const
{
	static const FSlateIcon Icon(FAppStyle::GetAppStyleSetName(), TEXT("Kismet.AllClasses.FunctionIcon"));
	return Icon;
}

void UK2Node_SetNamedPrimitiveData::GetMenuActions(FBlueprintActionDatabaseRegistrar& ActionRegistrar) const
{
	UClass* ActionKey = GetClass();
	if (ActionRegistrar.IsOpenForRegistration(ActionKey))
	{
		UBlueprintNodeSpawner* Spawner = UBlueprintNodeSpawner::Create(ActionKey);
		check(Spawner);
		ActionRegistrar.AddBlueprintAction(ActionKey, Spawner);
	}
}

FText UK2Node_SetNamedPrimitiveData::GetMenuCategory() const
{
	// Beside the engine's own SetCustomPrimitiveData* functions.
	return LOCTEXT("Category", "Rendering|Material");
}

FText UK2Node_SetNamedPrimitiveData::GetKeywords() const
{
	return LOCTEXT("Keywords", "custom primitive data cpd legend named legend parameter set");
}

// ---------------------------------------------------------------------------
// Compilation
// ---------------------------------------------------------------------------

void UK2Node_SetNamedPrimitiveData::ValidateNodeDuringCompilation(FCompilerResultsLog& MessageLog) const
{
	Super::ValidateNodeDuringCompilation(MessageLog);

	const UPrimitiveDataLegend* Legend = GetLegend();
	if (!Legend)
	{
		MessageLog.Error(*LOCTEXT("NoLegend", "@@ has no Primitive Data Legend chosen.").ToString(), this);
		return;
	}

	const FPrimitiveDataLegendEntry* Entry = ResolveParameter();
	if (!Entry)
	{
		MessageLog.Error(*FText::Format(
			LOCTEXT("NoParameter", "@@: parameter '{0}' is not in {1}."),
			FText::FromName(ParameterName), FText::FromString(Legend->GetName())).ToString(), this);
		return;
	}
	if (!Entry->HasSlot())
	{
		MessageLog.Error(*FText::Format(
			LOCTEXT("NoSlot", "@@: '{0}' has no slot in {1} - the legend is out of room. Open it for details."),
			FText::FromName(Entry->Name), FText::FromString(Legend->GetName())).ToString(), this);
		return;
	}
	if (KindOf(Entry) != ValueKind)
	{
		MessageLog.Error(*FText::Format(
			LOCTEXT("StaleKind", "@@: '{0}' changed type in {1}. Refresh the node (right-click > Refresh Nodes)."),
			FText::FromName(Entry->Name), FText::FromString(Legend->GetName())).ToString(), this);
		return;
	}

	// NOT checked here: whether Target is connected. The compiler validates AFTER expansion, by which
	// point ExpandNode has handed every link to the intermediate call and this node has none - so a
	// link check here fails on every correctly wired node. It lives in ExpandNode, before the move.
}

void UK2Node_SetNamedPrimitiveData::ExpandNode(FKismetCompilerContext& CompilerContext, UEdGraph* SourceGraph)
{
	Super::ExpandNode(CompilerContext, SourceGraph);

	const UEdGraphSchema_K2* Schema = CompilerContext.GetSchema();
	const FPrimitiveDataLegendEntry* Entry = ResolveParameter();
	UEdGraphPin* Value = FindPin(ValuePinName);

	// ValidateNodeDuringCompilation has already said why; all that is left is to not emit anything.
	if (!Entry || !Entry->HasSlot() || !Value || KindOf(Entry) != ValueKind)
	{
		BreakAllNodeLinks();
		return;
	}

	// Unwired Target means "self", as on any engine node - fine when this Blueprint IS a primitive
	// component, an error anywhere else. Checked here rather than left to the intermediate call so the
	// message names this node, not a node the user never placed.
	UEdGraphPin* Target = FindPinChecked(TargetPinName);
	if (Target->LinkedTo.Num() == 0)
	{
		const UClass* Context = CompilerContext.Blueprint ? CompilerContext.Blueprint->ParentClass : nullptr;
		if (!Context || !Context->IsChildOf(UPrimitiveComponent::StaticClass()))
		{
			CompilerContext.MessageLog.Error(*LOCTEXT("NoTarget", "@@ needs a mesh connected to Target.").ToString(), this);
			BreakAllNodeLinks();
			return;
		}
	}

	const bool bVector = (ValueKind == ENamedPrimitiveDataValueKind::Vector);

	UK2Node_CallFunction* Set = CompilerContext.SpawnIntermediateNode<UK2Node_CallFunction>(this, SourceGraph);
	FName Function;
	if (bWriteDefaults)
	{
		Function = bVector
			? GET_FUNCTION_NAME_CHECKED(UPrimitiveComponent, SetDefaultCustomPrimitiveDataVector4)
			: GET_FUNCTION_NAME_CHECKED(UPrimitiveComponent, SetDefaultCustomPrimitiveDataFloat);
	}
	else
	{
		Function = bVector
			? GET_FUNCTION_NAME_CHECKED(UPrimitiveComponent, SetCustomPrimitiveDataVector4)
			: GET_FUNCTION_NAME_CHECKED(UPrimitiveComponent, SetCustomPrimitiveDataFloat);
	}
	Set->FunctionReference.SetExternalMember(Function, UPrimitiveComponent::StaticClass());
	Set->AllocateDefaultPins();

	CompilerContext.MovePinLinksToIntermediate(*GetExecPin(), *Set->GetExecPin());
	CompilerContext.MovePinLinksToIntermediate(*FindPinChecked(UEdGraphSchema_K2::PN_Then), *Set->GetThenPin());
	CompilerContext.MovePinLinksToIntermediate(*Target, *Set->FindPinChecked(UEdGraphSchema_K2::PN_Self));

	// THE point of the node: the slot is a literal, decided now, never looked up at runtime.
	Schema->TrySetDefaultValue(*Set->FindPinChecked(TEXT("DataIndex")), FString::FromInt(Entry->Slot));

	if (!bVector)
	{
		CompilerContext.MovePinLinksToIntermediate(*Value, *Set->FindPinChecked(TEXT("Value")));
	}
	else
	{
		// FLinearColor -> FVector4. The engine has no single conversion for this, so it is BreakColor
		// into MakeVector4: both are engine functions, which keeps the cooked Blueprint free of any
		// dependency on this plugin.
		UK2Node_CallFunction* Break = CompilerContext.SpawnIntermediateNode<UK2Node_CallFunction>(this, SourceGraph);
		Break->FunctionReference.SetExternalMember(
			GET_FUNCTION_NAME_CHECKED(UKismetMathLibrary, BreakColor), UKismetMathLibrary::StaticClass());
		Break->AllocateDefaultPins();

		UK2Node_CallFunction* Make = CompilerContext.SpawnIntermediateNode<UK2Node_CallFunction>(this, SourceGraph);
		Make->FunctionReference.SetExternalMember(
			GET_FUNCTION_NAME_CHECKED(UKismetMathLibrary, MakeVector4), UKismetMathLibrary::StaticClass());
		Make->AllocateDefaultPins();

		// Moves the default colour too, when nothing is connected.
		CompilerContext.MovePinLinksToIntermediate(*Value, *Break->FindPinChecked(TEXT("InColor")));

		const TPair<const TCHAR*, const TCHAR*> Channels[] = {
			{ TEXT("R"), TEXT("X") }, { TEXT("G"), TEXT("Y") }, { TEXT("B"), TEXT("Z") }, { TEXT("A"), TEXT("W") } };
		bool bWired = true;
		for (const TPair<const TCHAR*, const TCHAR*>& Channel : Channels)
		{
			bWired &= Schema->TryCreateConnection(Break->FindPinChecked(Channel.Key), Make->FindPinChecked(Channel.Value));
		}
		bWired &= Schema->TryCreateConnection(Make->GetReturnValuePin(), Set->FindPinChecked(TEXT("Value")));

		if (!bWired)
		{
			CompilerContext.MessageLog.Error(
				*LOCTEXT("WireFailed", "@@: internal error converting the colour for the Vector4 set.").ToString(), this);
		}
	}

	BreakAllNodeLinks();
}

#undef LOCTEXT_NAMESPACE
