#include "K2Node_SetNamedInstanceDataMulti.h"

#include "BlueprintActionDatabaseRegistrar.h"
#include "BlueprintNodeSpawner.h"
#include "Components/InstancedStaticMeshComponent.h"
#include "EdGraphSchema_K2.h"
#include "InstanceDataSetLibrary.h"
#include "K2Node_CallFunction.h"
#include "Kismet2/BlueprintEditorUtils.h"
#include "Kismet2/CompilerResultsLog.h"
#include "KismetCompiler.h"
#include "NamedDataNodeExpansion.h"
#include "Styling/AppStyle.h"

#define LOCTEXT_NAMESPACE "K2Node_SetNamedInstanceDataMulti"

const FName UK2Node_SetNamedInstanceDataMulti::TargetPinName(UEdGraphSchema_K2::PN_Self);
const FName UK2Node_SetNamedInstanceDataMulti::InstanceIndexPinName(TEXT("InstanceIndex"));
const FName UK2Node_SetNamedInstanceDataMulti::LegendPinName(TEXT("Legend"));
const FName UK2Node_SetNamedInstanceDataMulti::MarkRenderStateDirtyPinName(TEXT("bMarkRenderStateDirty"));

namespace SetNamedInstanceDataMulti
{
	const TCHAR* DefaultColor = TEXT("(R=1.000000,G=1.000000,B=1.000000,A=1.000000)");
	const TCHAR* DefaultScalar = TEXT("0.0");

	ENamedPrimitiveDataValueKind KindOf(const FInstanceDataLegendEntry* Entry)
	{
		if (!Entry)
		{
			return ENamedPrimitiveDataValueKind::None;
		}
		return Entry->Type == EInstanceDataParameterType::Vector
			? ENamedPrimitiveDataValueKind::Vector
			: ENamedPrimitiveDataValueKind::Scalar;
	}
}

// ---------------------------------------------------------------------------
// Pins
// ---------------------------------------------------------------------------

FName UK2Node_SetNamedInstanceDataMulti::PinNameFor(const FGuid& Id)
{
	return FName(*FString::Printf(TEXT("Param_%s"), *Id.ToString(EGuidFormats::Digits)));
}

void UK2Node_SetNamedInstanceDataMulti::AllocateDefaultPins()
{
	CreatePin(EGPD_Input, UEdGraphSchema_K2::PC_Exec, UEdGraphSchema_K2::PN_Execute);
	CreatePin(EGPD_Output, UEdGraphSchema_K2::PC_Exec, UEdGraphSchema_K2::PN_Then);

	UEdGraphPin* Target = CreatePin(EGPD_Input, UEdGraphSchema_K2::PC_Object, UInstancedStaticMeshComponent::StaticClass(), TargetPinName);
	Target->PinFriendlyName = LOCTEXT("TargetName", "Target");
	Target->PinToolTip = LOCTEXT("TargetTooltip",
		"The instanced static mesh to set the data on. Wire in several, or an array, to set the same instance on each.").ToString();

	UEdGraphPin* Instance = CreatePin(EGPD_Input, UEdGraphSchema_K2::PC_Int, InstanceIndexPinName);
	Instance->PinToolTip = LOCTEXT("InstanceTooltip", "Which instance to set the data on.").ToString();
	GetDefault<UEdGraphSchema_K2>()->SetPinAutogeneratedDefaultValue(Instance, TEXT("0"));

	UEdGraphPin* Legend = CreatePin(EGPD_Input, UEdGraphSchema_K2::PC_Object, UInstanceDataLegend::StaticClass(), LegendPinName);
	Legend->bNotConnectable = true;
	Legend->PinToolTip = LOCTEXT("LegendTooltip",
		"The Instance Data Legend that names the parameters. Tick the ones to set in the Details panel.").ToString();

	for (const FNamedPrimitiveDataSelection& Selected : Selection)
	{
		CreateValuePin(Selected);
	}

	UEdGraphPin* Dirty = CreatePin(EGPD_Input, UEdGraphSchema_K2::PC_Boolean, MarkRenderStateDirtyPinName);
	Dirty->PinFriendlyName = LOCTEXT("DirtyName", "Mark Render State Dirty");
	Dirty->PinToolTip = LOCTEXT("DirtyTooltip",
		"Rebuild the mesh's render state now. Not needed for the change to show; expensive, so not every frame.").ToString();
	Dirty->bAdvancedView = true;
	GetDefault<UEdGraphSchema_K2>()->SetPinAutogeneratedDefaultValue(Dirty, TEXT("false"));
	if (AdvancedPinDisplay == ENodeAdvancedPins::NoPins)
	{
		AdvancedPinDisplay = ENodeAdvancedPins::Hidden;
	}

	Super::AllocateDefaultPins();
}

void UK2Node_SetNamedInstanceDataMulti::CreateValuePin(const FNamedPrimitiveDataSelection& Selected)
{
	UEdGraphPin* Value = nullptr;
	switch (Selected.Kind)
	{
	case ENamedPrimitiveDataValueKind::Scalar:
		Value = CreatePin(EGPD_Input, UEdGraphSchema_K2::PC_Real, UEdGraphSchema_K2::PC_Float, PinNameFor(Selected.Id));
		GetDefault<UEdGraphSchema_K2>()->SetPinAutogeneratedDefaultValue(Value, SetNamedInstanceDataMulti::DefaultScalar);
		break;
	case ENamedPrimitiveDataValueKind::Vector:
		Value = CreatePin(EGPD_Input, UEdGraphSchema_K2::PC_Struct, TBaseStructure<FLinearColor>::Get(), PinNameFor(Selected.Id));
		GetDefault<UEdGraphSchema_K2>()->SetPinAutogeneratedDefaultValue(Value, SetNamedInstanceDataMulti::DefaultColor);
		break;
	default:
		// No longer in the legend: no pin, and validation says why.
		return;
	}
	Value->PinFriendlyName = FText::FromName(Selected.Name);
}

void UK2Node_SetNamedInstanceDataMulti::PostReconstructNode()
{
	Super::PostReconstructNode();

	// Here rather than as the pins are made: during reconstruction the Legend pin has no value yet.
	const UInstanceDataLegend* Legend = GetLegend();
	for (const FNamedPrimitiveDataSelection& Selected : Selection)
	{
		UEdGraphPin* Value = FindValuePin(Selected.Id);
		const FInstanceDataLegendEntry* Entry = Resolve(Legend, Selected);
		if (Value && Entry && Entry->HasSlot())
		{
			Value->PinToolTip = Entry->GetWidth() > 1
				? FString::Printf(TEXT("%s (slots %d-%d; alpha is not stored)"), *Selected.Name.ToString(), Entry->Slot, Entry->Slot + Entry->GetWidth() - 1)
				: FString::Printf(TEXT("%s (slot %d)"), *Selected.Name.ToString(), Entry->Slot);
		}
	}
}

UEdGraphPin* UK2Node_SetNamedInstanceDataMulti::FindPinIn(FName Name, const TArray<UEdGraphPin*>* InPins) const
{
	const TArray<UEdGraphPin*>& Search = InPins ? *InPins : Pins;
	for (UEdGraphPin* Pin : Search)
	{
		if (Pin && Pin->PinName == Name)
		{
			return Pin;
		}
	}
	return nullptr;
}

UEdGraphPin* UK2Node_SetNamedInstanceDataMulti::FindValuePin(const FGuid& Id) const
{
	return FindPinIn(PinNameFor(Id), nullptr);
}

UInstanceDataLegend* UK2Node_SetNamedInstanceDataMulti::GetLegend(const TArray<UEdGraphPin*>* InPins) const
{
	const UEdGraphPin* Pin = FindPinIn(LegendPinName, InPins);
	return Pin ? Cast<UInstanceDataLegend>(Pin->DefaultObject) : nullptr;
}

const FInstanceDataLegendEntry* UK2Node_SetNamedInstanceDataMulti::Resolve(const UInstanceDataLegend* Legend,
	const FNamedPrimitiveDataSelection& Selected) const
{
	if (!Legend)
	{
		return nullptr;
	}
	if (const FInstanceDataLegendEntry* ById = Legend->FindParameter(Selected.Id))
	{
		return ById;
	}
	return Selected.Name.IsNone() ? nullptr : Legend->FindParameter(Selected.Name);
}

// ---------------------------------------------------------------------------
// Selection
// ---------------------------------------------------------------------------

bool UK2Node_SetNamedInstanceDataMulti::IsParameterSelected(const FGuid& Id) const
{
	return Selection.ContainsByPredicate([&Id](const FNamedPrimitiveDataSelection& Selected) { return Selected.Id == Id; });
}

void UK2Node_SetNamedInstanceDataMulti::SetParameterSelected(const FGuid& Id, bool bSelected)
{
	if (IsParameterSelected(Id) == bSelected)
	{
		return;
	}

	Modify();
	if (bSelected)
	{
		Selection.AddDefaulted_GetRef().Id = Id;
	}
	else
	{
		Selection.RemoveAll([&Id](const FNamedPrimitiveDataSelection& Selected) { return Selected.Id == Id; });
		DropValuePin(Id);
	}
	RefreshSelection(nullptr);
	Rebuild();
}

void UK2Node_SetNamedInstanceDataMulti::DropValuePin(const FGuid& Id)
{
	// Removed outright: left to reconstruction, a pin with a wire would be kept as an orphan.
	if (UEdGraphPin* Pin = FindValuePin(Id))
	{
		Pin->BreakAllPinLinks();
		RemovePin(Pin);
	}
}

void UK2Node_SetNamedInstanceDataMulti::RefreshSelection(const TArray<UEdGraphPin*>* InPins)
{
	const UInstanceDataLegend* Legend = GetLegend(InPins);
	if (!Legend)
	{
		// Nothing to check against. Keep the selection, so choosing the legend again restores it.
		return;
	}

	for (FNamedPrimitiveDataSelection& Selected : Selection)
	{
		const FInstanceDataLegendEntry* Entry = Resolve(Legend, Selected);
		if (Entry)
		{
			Selected.Id = Entry->Id;
			Selected.Name = Entry->Name;
		}
		Selected.Kind = SetNamedInstanceDataMulti::KindOf(Entry);
	}

	// Pins in the legend's order, whatever order they were ticked in. Missing ones go last.
	auto IndexOf = [Legend](const FNamedPrimitiveDataSelection& Selected)
	{
		const int32 Index = Legend->Parameters.IndexOfByPredicate(
			[&Selected](const FInstanceDataLegendEntry& Entry) { return Entry.Id == Selected.Id; });
		return Index == INDEX_NONE ? MAX_int32 : Index;
	};
	Selection.StableSort([&IndexOf](const FNamedPrimitiveDataSelection& A, const FNamedPrimitiveDataSelection& B)
	{
		return IndexOf(A) < IndexOf(B);
	});
}

void UK2Node_SetNamedInstanceDataMulti::Rebuild()
{
	ReconstructNode();
	if (UEdGraph* Graph = GetGraph())
	{
		Graph->NotifyNodeChanged(this);
	}
	if (UBlueprint* Blueprint = FBlueprintEditorUtils::FindBlueprintForNode(this))
	{
		FBlueprintEditorUtils::MarkBlueprintAsModified(Blueprint);
	}
}

void UK2Node_SetNamedInstanceDataMulti::PinDefaultValueChanged(UEdGraphPin* Pin)
{
	Super::PinDefaultValueChanged(Pin);
	if (!Pin || Pin->PinName != LegendPinName)
	{
		return;
	}

	// A new legend: keep every ticked parameter it also has (by id, or by name), drop the rest.
	Modify();
	const UInstanceDataLegend* Legend = GetLegend();
	Selection.RemoveAll([this, Legend](const FNamedPrimitiveDataSelection& Selected)
	{
		if (Resolve(Legend, Selected))
		{
			return false;
		}
		DropValuePin(Selected.Id);
		return true;
	});
	RefreshSelection(nullptr);
	Rebuild();
	OnParametersOffered.Broadcast();
}

void UK2Node_SetNamedInstanceDataMulti::ReallocatePinsDuringReconstruction(TArray<UEdGraphPin*>& OldPins)
{
	if (UInstanceDataLegend* Legend = GetLegend(&OldPins))
	{
		PreloadObject(Legend);
	}
	RefreshSelection(&OldPins);

	Super::ReallocatePinsDuringReconstruction(OldPins);
}

UK2Node::ERedirectType UK2Node_SetNamedInstanceDataMulti::DoPinsMatchForReconstruction(const UEdGraphPin* NewPin,
	int32 NewPinIndex, const UEdGraphPin* OldPin, int32 OldPinIndex) const
{
	if (NewPin && OldPin && NewPin->Direction == OldPin->Direction && NewPin->PinName == OldPin->PinName)
	{
		// A parameter whose type changed in the legend: let its wire and value go rather than carry a colour into a float.
		const bool bSameType = NewPin->PinType.PinCategory == OldPin->PinType.PinCategory
			&& NewPin->PinType.PinSubCategoryObject == OldPin->PinType.PinSubCategoryObject;
		if (!bSameType)
		{
			return ERedirectType_None;
		}
	}
	return Super::DoPinsMatchForReconstruction(NewPin, NewPinIndex, OldPin, OldPinIndex);
}

void UK2Node_SetNamedInstanceDataMulti::PreloadRequiredAssets()
{
	if (UInstanceDataLegend* Legend = GetLegend())
	{
		PreloadObject(Legend);
	}
	Super::PreloadRequiredAssets();
}

bool UK2Node_SetNamedInstanceDataMulti::GetWriteRange(int32& OutFirst, int32& OutCount, uint64& OutMask) const
{
	OutFirst = 0;
	OutCount = 0;
	OutMask = 0;

	const UInstanceDataLegend* Legend = GetLegend();
	int32 First = MAX_int32;
	int32 End = 0;
	for (const FNamedPrimitiveDataSelection& Selected : Selection)
	{
		const FInstanceDataLegendEntry* Entry = Resolve(Legend, Selected);
		if (Entry && Entry->HasSlot())
		{
			First = FMath::Min(First, Entry->Slot);
			End = FMath::Max(End, Entry->Slot + Entry->GetWidth());
		}
	}
	if (First == MAX_int32)
	{
		return false;
	}

	// A legend lays out at most 64 floats, so the range always fits the mask.
	for (const FNamedPrimitiveDataSelection& Selected : Selection)
	{
		const FInstanceDataLegendEntry* Entry = Resolve(Legend, Selected);
		if (Entry && Entry->HasSlot())
		{
			for (int32 Float = 0; Float < Entry->GetWidth(); ++Float)
			{
				OutMask |= uint64(1) << (Entry->Slot - First + Float);
			}
		}
	}
	OutFirst = First;
	OutCount = End - First;
	return true;
}

// ---------------------------------------------------------------------------
// Presentation
// ---------------------------------------------------------------------------

FText UK2Node_SetNamedInstanceDataMulti::GetNodeTitle(ENodeTitleType::Type TitleType) const
{
	if (TitleType == ENodeTitleType::FullTitle)
	{
		if (const UInstanceDataLegend* Legend = GetLegend())
		{
			return FText::Format(LOCTEXT("TitleWithLegend", "Set Named Instance Data (Multiple)\n{0}"), FText::FromString(Legend->GetName()));
		}
	}
	return LOCTEXT("Title", "Set Named Instance Data (Multiple)");
}

FText UK2Node_SetNamedInstanceDataMulti::GetTooltipText() const
{
	return LOCTEXT("Tooltip",
		"Set several per instance custom data parameters on an instance of an instanced static mesh in a single "
		"write, chosen by name from an Instance Data Legend. Tick the parameters in the Details panel.\n\n"
		"Floats between the ticked parameters keep their current values. The mesh needs at least the legend's "
		"Floats Per Instance in its Num Custom Data Floats.");
}

FSlateIcon UK2Node_SetNamedInstanceDataMulti::GetIconAndTint(FLinearColor& OutColor) const
{
	static const FSlateIcon Icon(FAppStyle::GetAppStyleSetName(), TEXT("Kismet.AllClasses.FunctionIcon"));
	return Icon;
}

void UK2Node_SetNamedInstanceDataMulti::GetMenuActions(FBlueprintActionDatabaseRegistrar& ActionRegistrar) const
{
	UClass* ActionKey = GetClass();
	if (ActionRegistrar.IsOpenForRegistration(ActionKey))
	{
		UBlueprintNodeSpawner* Spawner = UBlueprintNodeSpawner::Create(ActionKey);
		check(Spawner);
		ActionRegistrar.AddBlueprintAction(ActionKey, Spawner);
	}
}

FText UK2Node_SetNamedInstanceDataMulti::GetMenuCategory() const
{
	return LOCTEXT("Category", "Components|InstancedStaticMesh");
}

FText UK2Node_SetNamedInstanceDataMulti::GetKeywords() const
{
	return LOCTEXT("Keywords", "per instance custom data picd ism hism instanced legend named parameter set multiple several many batch");
}

// ---------------------------------------------------------------------------
// Compilation
// ---------------------------------------------------------------------------

void UK2Node_SetNamedInstanceDataMulti::ValidateNodeDuringCompilation(FCompilerResultsLog& MessageLog) const
{
	Super::ValidateNodeDuringCompilation(MessageLog);

	const UInstanceDataLegend* Legend = GetLegend();
	if (!Legend)
	{
		MessageLog.Error(*LOCTEXT("NoLegend", "@@ has no Instance Data Legend chosen.").ToString(), this);
		return;
	}
	if (Selection.Num() == 0)
	{
		MessageLog.Error(*LOCTEXT("NothingTicked", "@@ sets nothing - tick its parameters in the Details panel.").ToString(), this);
		return;
	}
	for (const FNamedPrimitiveDataSelection& Selected : Selection)
	{
		const FInstanceDataLegendEntry* Entry = Resolve(Legend, Selected);
		if (!Entry)
		{
			MessageLog.Error(*FText::Format(LOCTEXT("NoParameter", "@@: parameter '{0}' is not in {1}."),
				FText::FromName(Selected.Name), FText::FromString(Legend->GetName())).ToString(), this);
		}
		else if (!Entry->HasSlot())
		{
			MessageLog.Error(*FText::Format(
				LOCTEXT("NoSlot", "@@: '{0}' has no slot in {1} - the legend is out of room. Open it for details."),
				FText::FromName(Entry->Name), FText::FromString(Legend->GetName())).ToString(), this);
		}
		else if (SetNamedInstanceDataMulti::KindOf(Entry) != Selected.Kind)
		{
			MessageLog.Error(*FText::Format(
				LOCTEXT("StaleKind", "@@: '{0}' changed type in {1}. Refresh the node (right-click > Refresh Nodes)."),
				FText::FromName(Entry->Name), FText::FromString(Legend->GetName())).ToString(), this);
		}
	}
}

void UK2Node_SetNamedInstanceDataMulti::ExpandNode(FKismetCompilerContext& CompilerContext, UEdGraph* SourceGraph)
{
	Super::ExpandNode(CompilerContext, SourceGraph);

	const UEdGraphSchema_K2* Schema = CompilerContext.GetSchema();
	const UInstanceDataLegend* Legend = GetLegend();

	// Validation says why for each of these; all that is left is to emit nothing.
	TArray<NamedDataNodeExpansion::FValueWrite> Writes;
	bool bValid = Legend != nullptr && Selection.Num() > 0;
	for (const FNamedPrimitiveDataSelection& Selected : Selection)
	{
		const FInstanceDataLegendEntry* Entry = Resolve(Legend, Selected);
		UEdGraphPin* Pin = FindValuePin(Selected.Id);
		if (!Entry || !Entry->HasSlot() || !Pin || SetNamedInstanceDataMulti::KindOf(Entry) != Selected.Kind)
		{
			bValid = false;
			break;
		}
		Writes.Add({ Pin, Entry->Slot, Entry->GetWidth() });
	}
	int32 First = 0;
	int32 Count = 0;
	uint64 Mask = 0;
	if (!bValid || !GetWriteRange(First, Count, Mask))
	{
		BreakAllNodeLinks();
		return;
	}
	for (NamedDataNodeExpansion::FValueWrite& Write : Writes)
	{
		Write.Offset -= First;
	}

	UEdGraphPin* Target = FindPinChecked(TargetPinName);
	if (!NamedDataNodeExpansion::CheckSelfTarget(CompilerContext, this, Target, UInstancedStaticMeshComponent::StaticClass(),
		LOCTEXT("NoTarget", "@@ needs an instanced static mesh connected to Target.")))
	{
		BreakAllNodeLinks();
		return;
	}

	UK2Node_CallFunction* Set = CompilerContext.SpawnIntermediateNode<UK2Node_CallFunction>(this, SourceGraph);
	Set->SetFromFunction(UInstanceDataSetLibrary::StaticClass()->FindFunctionByName(
		GET_FUNCTION_NAME_CHECKED(UInstanceDataSetLibrary, SetInstanceCustomDataMasked)));
	Set->AllocateDefaultPins();
	if (!Set->GetTargetFunction())
	{
		CompilerContext.MessageLog.Error(*LOCTEXT("MissingFunction",
			"@@: internal error - the instance data function to call was not found.").ToString(), this);
		BreakAllNodeLinks();
		return;
	}

	CompilerContext.MovePinLinksToIntermediate(*GetExecPin(), *Set->GetExecPin());
	CompilerContext.MovePinLinksToIntermediate(*FindPinChecked(UEdGraphSchema_K2::PN_Then), *Set->GetThenPin());
	CompilerContext.MovePinLinksToIntermediate(*FindPinChecked(InstanceIndexPinName), *Set->FindPinChecked(TEXT("InstanceIndex")));
	CompilerContext.MovePinLinksToIntermediate(*FindPinChecked(MarkRenderStateDirtyPinName), *Set->FindPinChecked(TEXT("bMarkRenderStateDirty")));

	// The slot and the mask are literals, decided now.
	Schema->TrySetDefaultValue(*Set->FindPinChecked(TEXT("DataIndex")), FString::FromInt(First));
	Schema->TrySetDefaultValue(*Set->FindPinChecked(TEXT("Mask")), FString::Printf(TEXT("%lld"), static_cast<int64>(Mask)));

	bool bWired = true;
	if (!NamedDataNodeExpansion::GatherTargets(CompilerContext, this, SourceGraph, Target, Set->FindPinChecked(TEXT("Targets")), bWired))
	{
		BreakAllNodeLinks();
		return;
	}
	bWired &= NamedDataNodeExpansion::WireValues(CompilerContext, this, SourceGraph, Set->FindPinChecked(TEXT("Values")), Count, Writes);

	if (!bWired)
	{
		CompilerContext.MessageLog.Error(*LOCTEXT("WireFailed", "@@: internal error wiring the instance data write.").ToString(), this);
	}
	BreakAllNodeLinks();
}

#undef LOCTEXT_NAMESPACE
