#include "K2Node_WebState.h"

#include "CodeAnimationWeb.h"
#include "EdGraphSchema_K2.h"
#include "K2Node_CallFunction.h"
#include "K2Node_CastByteToEnum.h"
#include "Kismet2/CompilerResultsLog.h"
#include "KismetCompiler.h"

#define LOCTEXT_NAMESPACE "K2Node_WebState"

const FName UK2Node_SetWebState::StatePinName(TEXT("State"));
const FName UK2Node_SetWebState::InstantPinName(TEXT("Instant"));
const FName UK2Node_SetWebState::SuccessPinName(TEXT("Success"));

UEnum* CodeAnimWebNodes::GetStateEnum(const UClass* WebClass)
{
	const UCodeAnimationWeb* Defaults = WebClass ? Cast<UCodeAnimationWeb>(WebClass->GetDefaultObject()) : nullptr;
	return Defaults ? Defaults->StateEnum.Get() : nullptr;
}

namespace WebStateNodes
{
	/** Retypes a byte pin to an enum, resetting what no longer fits. */
	static void Retype(UEdGraphPin* Pin, UEnum* Enum, bool bSetDefault)
	{
		if (!Pin || Pin->PinType.PinSubCategoryObject == Enum)
		{
			return;
		}
		Pin->Modify();
		Pin->BreakAllPinLinks();
		Pin->PinType.PinSubCategoryObject = Enum;
		if (bSetDefault)
		{
			const FString Default = Enum && Enum->NumEnums() > 1 ? Enum->GetNameStringByIndex(0) : TEXT("0");
			GetDefault<UEdGraphSchema_K2>()->SetPinAutogeneratedDefaultValue(Pin, Default);
		}
	}
}

// ---------------------------------------------------------------------------
// Set Web State
// ---------------------------------------------------------------------------

void UK2Node_SetWebState::AllocateDefaultPins()
{
	CreatePin(EGPD_Input, UEdGraphSchema_K2::PC_Exec, UEdGraphSchema_K2::PN_Execute);
	CreatePin(EGPD_Output, UEdGraphSchema_K2::PC_Exec, UEdGraphSchema_K2::PN_Then);
	CreateWebPin();

	UEdGraphPin* State = CreatePin(EGPD_Input, UEdGraphSchema_K2::PC_Byte, StateEnum.Get(), StatePinName);
	State->PinToolTip = LOCTEXT("StateTooltip", "The state to head for.").ToString();
	GetDefault<UEdGraphSchema_K2>()->SetPinAutogeneratedDefaultValue(State,
		StateEnum && StateEnum->NumEnums() > 1 ? StateEnum->GetNameStringByIndex(0) : TEXT("0"));

	UEdGraphPin* Instant = CreatePin(EGPD_Input, UEdGraphSchema_K2::PC_Boolean, InstantPinName);
	Instant->PinToolTip = LOCTEXT("InstantTooltip", "Jump straight there, with no transition.").ToString();
	GetDefault<UEdGraphSchema_K2>()->SetPinAutogeneratedDefaultValue(Instant, TEXT("false"));

	UEdGraphPin* Success = CreatePin(EGPD_Output, UEdGraphSchema_K2::PC_Boolean, SuccessPinName);
	Success->PinToolTip = LOCTEXT("SuccessTooltip",
		"False if refused: the Web is paused or headed for a pause, or (Transition Traversal Only) no transitions lead there.").ToString();

	Super::AllocateDefaultPins();
}

void UK2Node_SetWebState::OnWebClassChanged()
{
	UEnum* NewEnum = CodeAnimWebNodes::GetStateEnum(WebClass);
	if (WebClass && NewEnum != StateEnum)
	{
		StateEnum = NewEnum;
		WebStateNodes::Retype(FindPin(StatePinName), StateEnum, /*bSetDefault*/ true);
	}
}

void UK2Node_SetWebState::ReallocatePinsDuringReconstruction(TArray<UEdGraphPin*>& OldPins)
{
	if (WebClass)
	{
		PreloadObject(WebClass);
		StateEnum = CodeAnimWebNodes::GetStateEnum(WebClass);
	}
	Super::ReallocatePinsDuringReconstruction(OldPins);
}

FText UK2Node_SetWebState::GetNodeTitle(ENodeTitleType::Type TitleType) const
{
	if (TitleType == ENodeTitleType::FullTitle && WebClass)
	{
		return FText::Format(LOCTEXT("SetTitleWithClass", "Set Web State\n{0}"), WebClass->GetDisplayNameText());
	}
	return LOCTEXT("SetTitle", "Set Web State");
}

FText UK2Node_SetWebState::GetTooltipText() const
{
	return LOCTEXT("SetTooltip", "Head the Web for a state. Setting the state it is already heading for does nothing.");
}

FText UK2Node_SetWebState::GetKeywords() const
{
	return LOCTEXT("SetKeywords", "code animation web set state change");
}

void UK2Node_SetWebState::ExpandNode(FKismetCompilerContext& CompilerContext, UEdGraph* SourceGraph)
{
	Super::ExpandNode(CompilerContext, SourceGraph);
	if (!CheckWebSource(CompilerContext))
	{
		BreakAllNodeLinks();
		return;
	}

	const UEdGraphSchema_K2* Schema = CompilerContext.GetSchema();
	UK2Node_CallFunction* Call = CompilerContext.SpawnIntermediateNode<UK2Node_CallFunction>(this, SourceGraph);
	Call->FunctionReference.SetExternalMember(GetTargetFunctionName(), UCodeAnimationWeb::StaticClass());
	Call->AllocateDefaultPins();

	CompilerContext.MovePinLinksToIntermediate(*GetExecPin(), *Call->GetExecPin());
	CompilerContext.MovePinLinksToIntermediate(*FindPinChecked(UEdGraphSchema_K2::PN_Then), *Call->GetThenPin());
	CompilerContext.MovePinLinksToIntermediate(*FindPinChecked(WebPinName), *Call->FindPinChecked(UEdGraphSchema_K2::PN_Self));
	CompilerContext.MovePinLinksToIntermediate(*FindPinChecked(InstantPinName), *Call->FindPinChecked(TEXT("bInstant")));
	CompilerContext.MovePinLinksToIntermediate(*FindPinChecked(SuccessPinName), *Call->GetReturnValuePin());

	UEdGraphPin* State = FindPinChecked(StatePinName);
	UEdGraphPin* NewState = Call->FindPinChecked(TEXT("NewState"));
	if (State->LinkedTo.Num() > 0)
	{
		CompilerContext.MovePinLinksToIntermediate(*State, *NewState);
	}
	else
	{
		// The literal is an enumerator name; SetState wants its value.
		int64 Value = StateEnum ? StateEnum->GetValueByNameString(State->DefaultValue) : FCString::Atoi64(*State->DefaultValue);
		if (Value == INDEX_NONE)
		{
			CompilerContext.MessageLog.Error(*FText::Format(LOCTEXT("BadState", "@@: '{0}' is not one of the Web's states."),
				FText::FromString(State->DefaultValue)).ToString(), this);
			Value = 0;
		}
		Schema->TrySetDefaultValue(*NewState, FString::FromInt(static_cast<int32>(Value)));
	}

	BreakAllNodeLinks();
}

FName UK2Node_SetWebState::GetTargetFunctionName() const
{
	return GET_FUNCTION_NAME_CHECKED(UCodeAnimationWeb, SetState);
}

// ---------------------------------------------------------------------------
// Pause Web In State
// ---------------------------------------------------------------------------

FText UK2Node_PauseWebInState::GetNodeTitle(ENodeTitleType::Type TitleType) const
{
	if (TitleType == ENodeTitleType::FullTitle && WebClass)
	{
		return FText::Format(LOCTEXT("PauseTitleWithClass", "Pause Web In State\n{0}"), WebClass->GetDisplayNameText());
	}
	return LOCTEXT("PauseTitle", "Pause Web In State");
}

FText UK2Node_PauseWebInState::GetTooltipText() const
{
	return LOCTEXT("PauseTooltip",
		"Head the Web for a state and pause it there: from now on Set Web State is refused, and when the Web arrives it "
		"freezes. Already there, it freezes at once. Set Paused (unticked) releases it.");
}

FText UK2Node_PauseWebInState::GetKeywords() const
{
	return LOCTEXT("PauseKeywords", "code animation web pause freeze lock hold state");
}

FName UK2Node_PauseWebInState::GetTargetFunctionName() const
{
	return GET_FUNCTION_NAME_CHECKED(UCodeAnimationWeb, PauseInState);
}

// ---------------------------------------------------------------------------
// Get Web State
// ---------------------------------------------------------------------------

void UK2Node_GetWebState::AllocateDefaultPins()
{
	CreateWebPin();
	UEdGraphPin* State = CreatePin(EGPD_Output, UEdGraphSchema_K2::PC_Byte, StateEnum.Get(), UEdGraphSchema_K2::PN_ReturnValue);
	State->PinFriendlyName = LOCTEXT("State", "State");
	Super::AllocateDefaultPins();
}

void UK2Node_GetWebState::OnWebClassChanged()
{
	UEnum* NewEnum = CodeAnimWebNodes::GetStateEnum(WebClass);
	if (WebClass && NewEnum != StateEnum)
	{
		StateEnum = NewEnum;
		WebStateNodes::Retype(FindPin(UEdGraphSchema_K2::PN_ReturnValue), StateEnum, /*bSetDefault*/ false);
	}
}

void UK2Node_GetWebState::ReallocatePinsDuringReconstruction(TArray<UEdGraphPin*>& OldPins)
{
	if (WebClass)
	{
		PreloadObject(WebClass);
		StateEnum = CodeAnimWebNodes::GetStateEnum(WebClass);
	}
	Super::ReallocatePinsDuringReconstruction(OldPins);
}

FText UK2Node_GetWebState::GetNodeTitle(ENodeTitleType::Type TitleType) const
{
	if (TitleType == ENodeTitleType::FullTitle && WebClass)
	{
		return FText::Format(LOCTEXT("GetTitleWithClass", "Get Web State\n{0}"), WebClass->GetDisplayNameText());
	}
	return LOCTEXT("GetTitle", "Get Web State");
}

FText UK2Node_GetWebState::GetTooltipText() const
{
	return LOCTEXT("GetTooltip", "The state the Web is heading for, or sitting in.");
}

FText UK2Node_GetWebState::GetKeywords() const
{
	return LOCTEXT("GetKeywords", "code animation web get state current");
}

void UK2Node_GetWebState::ExpandNode(FKismetCompilerContext& CompilerContext, UEdGraph* SourceGraph)
{
	Super::ExpandNode(CompilerContext, SourceGraph);
	if (!CheckWebSource(CompilerContext))
	{
		BreakAllNodeLinks();
		return;
	}

	const UEdGraphSchema_K2* Schema = CompilerContext.GetSchema();
	UK2Node_CallFunction* Call = CompilerContext.SpawnIntermediateNode<UK2Node_CallFunction>(this, SourceGraph);
	Call->FunctionReference.SetExternalMember(GET_FUNCTION_NAME_CHECKED(UCodeAnimationWeb, GetState), UCodeAnimationWeb::StaticClass());
	Call->AllocateDefaultPins();
	CompilerContext.MovePinLinksToIntermediate(*FindPinChecked(WebPinName), *Call->FindPinChecked(UEdGraphSchema_K2::PN_Self));

	UEdGraphPin* Result = FindPinChecked(UEdGraphSchema_K2::PN_ReturnValue);
	if (StateEnum)
	{
		UK2Node_CastByteToEnum* ToEnum = CompilerContext.SpawnIntermediateNode<UK2Node_CastByteToEnum>(this, SourceGraph);
		ToEnum->Enum = StateEnum;
		ToEnum->bSafe = false;
		ToEnum->AllocateDefaultPins();
		if (!Schema->TryCreateConnection(Call->GetReturnValuePin(), ToEnum->FindPinChecked(TEXT("Byte"))))
		{
			CompilerContext.MessageLog.Error(*LOCTEXT("WireFailed", "@@: internal error converting the state.").ToString(), this);
		}
		CompilerContext.MovePinLinksToIntermediate(*Result, *ToEnum->FindPinChecked(UEdGraphSchema_K2::PN_ReturnValue));
	}
	else
	{
		CompilerContext.MovePinLinksToIntermediate(*Result, *Call->GetReturnValuePin());
	}

	BreakAllNodeLinks();
}

#undef LOCTEXT_NAMESPACE
